### ISSUE TITLE
Gray scale colormap consistency with silx and perceptual uniform LUTs

### ISSUE THREAD

**Issue by vallsv** [silx-kit/h5web#1054]
### Describe the bug

The dark-to-light colors direction of the gray LUT should be consistent with the perceptual uniform LUTs.

First, because it makes it easy to switch from one to another.

Second, for consistency with ESRF tools, like silx view, and probably PyMca (i haven't' checked).

For now it's the reverse.

![Screenshot from 2022-04-04 18-54-23](https://user-images.githubusercontent.com/7579321/161594847-8e001fee-5222-4eb7-881c-e8d6c79a6aa9.png)

**Comment by loichuder** [comment]
Color schemes come directly from [d3-scale-chromatic](https://github.com/d3/d3-scale-chromatic#d3-scale-chromatic).

The _Greys_ scale is a particular case of [Sequential single-hue schemes](https://github.com/d3/d3-scale-chromatic#sequential-single-hue) which also includes _Blues_, _Greens_, ...

Would you expect all sequential single-hue to be inverted as well ?

**Comment by vallsv** [comment]
I would say yes, for the same reason.
And because i see reason not to do so, but i don't know any user of such look up table.

**Comment by loichuder** [comment]
Note that complete consistency cannot be achieved as `silx` uses single-hue schemes that blend to black:
![image](https://user-images.githubusercontent.com/42204205/161782718-58e8f99d-1e63-4e03-b21c-af84740a5d0a.png)

while d3-scale-chormatic single-hue schemes blend to white:
![image](https://user-images.githubusercontent.com/42204205/161783327-1264c217-54f1-4ec9-98ee-89009f7a2259.png)

So perhaps it would be misleading to make think that these are the same schemes ?

**Comment by vallsv** [comment]
To me the most important to fix is the grey one. Most of the other colormaps will not be used.

Tell me if that's something which can be changed and release before May 24?
Else i have to care about it on my side.
