### ISSUE TITLE
[SelectionZoom] Make the zoom area take the full height (width) if the drawn rectangle has no height (width)

### ISSUE THREAD

**Issue by vallsv** [silx-kit/h5web#1066]
Plotly allows to drag a rectangle to zoom with the mouse (as h5web but notice that the data outside fades to grey)
![image](https://user-images.githubusercontent.com/7579321/162962259-af478724-cfe7-4202-ad38-0a83ed41e838.png)

A very interesting feature that plotly has and h5web has not is the following: if the vertical location of the mouse is very close to the start (rectangle with no height), the zoom rectangle takes the full height (similar to axial zoom in h5web)  
![image](https://user-images.githubusercontent.com/7579321/162962305-1c72ae54-acb1-4716-8470-928aefae8bce.png)

This would be good to reuse, particularly in the case of curve plots.

**Comment by vallsv** [comment]
This can work in both horizontally (full height), or vertically (full width).

**Comment by loichuder** [comment]
In this end, this was implemented as a separate component `AxialSelectToZoom` (#1145) rather than as a special mode of `SelectToZoom`.
