### ISSUE TITLE
[SelectToZoom] Allow to specify a mouse button

### ISSUE THREAD

**Issue by vallsv** [silx-kit/h5web#1121]
Hi,

I want to implement silx interaction in the plot.

It sounds like the `SelectToZoom` interaction is working for any mouse button.

It would be good to limit the interaction to a specific button.

And as it's low cost, this used button could be selected by property.

As result i will be able to create a `SelectToZoom` interaction with a left mouse button only.

This start to be an important feature for me, as the plot is about to be integrated and used in production.
https://gitlab.esrf.fr/ui/daiquiri-tomo/-/issues/115

**Comment by axelboc** [comment]
A better, more flexible approach would be to capture right clicks before they reach the `SelectToZoom` handlers -- more specifically `pointerdown` events before the reach the event handler registered on the canvas by `SelectionTool`.

To do so, you can try to render a component inside `VisCanvas` and before `SelectToZoom`. In this component, register an `onPointerDown` event handler on the canvas with `useCanvasEvents`. Inside this handler, if the event is triggered by the right mouse, call [`evt.stopImmediatePropagation()`](https://devdocs.io/dom/event/stopimmediatepropagation).

---

If the need arises to draw a selection or select-to-zoom with the right mouse button, then we will consider making the mouse button configurable in `SelectionTool` and `SelectToZoom`. Though, I don't see this ever happening, as those are two highly uncommon interactions.

**Comment by axelboc** [comment]
```tsx
<VisCanvas>
  <CaptureRightMouseButton />
  <SelectToZoom />
</VisCanvas>
```

```tsx
function CaptureRightMouseButton() {
  const onPointerDown = useCallback((evt: CanvasEvent<PointerEvent>) => {
    if (evt.button === 2) {
      evt.stopImmediatePropagation();
    }
  });

  useCanvasEvents({ onPointerDown });
  return null;
}
```

**Comment by axelboc** [comment]
Sorry, the title of the issue confused me. You're right that drawing a selection with the right mouse button (or middle) should not be possible. We should definitely correct this. Though, I don't believe we should make the button configurable, as explained.

**Comment by loichuder** [comment]
With #1129, `SelectToZoom` now only works with the left button. 

As @axelboc argued, this is not configurable.
