### ISSUE TITLE
Allow plotting default datasets with shape (N,1) as line

### ISSUE THREAD

**Issue by bmaranville** [silx-kit/h5web#1125]
### Is your feature request related to a problem?

When a file is loaded for display and the default dataset is automatically plotted, if it has shape (N,1) there is no option to plot it as a line (must manually select the dataset by drilling down into the tree structure, then line slice is available if the data is directly plotted)

### Requested solution or feature

Allow same plotting options for automatically plotted datasets as manually selected?  Not sure if this is the right answer or not. 

### Alternatives you've considered

For consistency of handling we're using a dimension of 1 for point detectors at the facility (so that scans with 2D detector datasets would have dimensions ```(num_scan_points, det_dim_0, det_dim_1)```, 1D detector datasets would have dimensions ```(num_scan_points, det_dim_0)``` and datasets from point detectors have dimension ```(num_scan_points, 1)```)
We can't easily change this convention.

**Comment by bmaranville** [comment]
Here is an example file that shows the issue:
[live.sample.name6.zip](https://github.com/silx-kit/h5web/files/8845189/live.sample.name6.zip)

**Comment by axelboc** [comment]
@bmaranville is the v4 behaviour of the viewer described by Loïc what you were after?

**Comment by bmaranville** [comment]
Sure, it allows us to plot our data.  I don't love using the name "spectrum", since our scans are not over wavelengths but over angles, but that is a minor point.

**Comment by axelboc** [comment]
Right, I wonder if we could do something about this - i.e. just display `Line` and `Heatmap`  when the signal doesn't have an `interpretation` attribute.

**Comment by loichuder** [comment]
> Sure, it allows us to plot our data. I don't love using the name "spectrum", since our scans are not over wavelengths but over angles, but that is a minor point.

Yeah, this is a legacy from NeXus unfortunately. 1D plots are dubbed "spectrum" and 2D plots are dubbed "images" while the underlying data could not represent spectra or images.

**Comment by loichuder** [comment]
On a related note, fun fact: when the `default` point to a regular dataset (and not a NXData group), the visualisations from a regular dataset (i.e. not-NeXus) are displayed instead.

See the root group of https://h5web.panosc.eu/h5wasm?url=https://raw.githubusercontent.com/oasys-esrf-kit/dabam2d/main/data/dabam2d-001.h5
