### ISSUE TITLE
[Heatmap] Sort colour maps

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#114]

**Comment by loichuder** [comment]
As for now, there are given in the order of [d3-scale-chromatic](https://github.com/d3/d3-scale-chromatic/#diverging):
- Diverging
- Sequential (single hue)
- Sequential (multi-hue)
- Cyclical

**Comment by t20100** [comment]
A proposition:

A few main schemes on top to give quick access to one (or 2) of each kind, e.g.: greys, viridis, magma or plasma, sinebow or rainbow, one diverging.

And then all of them in the same order:
- Sequential (single hue)
- Sequential (multi-hue)
- Cyclical
- Diverging

And if possible a separator in the drop-down menu between each kind of sceme.
