### ISSUE TITLE
[Pan] Support panning with both left and middle mouse buttons

### ISSUE THREAD

**Issue by vallsv** [silx-kit/h5web#1143]
Here is the interaction i want to implement.

Just to let you know that it sounds like i can't describe the interaction this way.

Sounds like using twice `Pan` interlock the interaction. And probably twice `SelectToZoom`

No idea if there is a problem somehow. Or this that have to warn or fail.

```
function DefaultMouseInteraction(props: {
  zoomMode: boolean;
  panMode: boolean;
  disabled: boolean;
}) {
  console.log(props.panMode, props.zoomMode);
  return (
    <>
      <Pan disabled={!props.panMode || props.disabled} />
      <Pan disabled={props.panMode || props.disabled} modifierKey="Control" />
      <SelectToZoom disabled={!props.zoomMode || props.disabled} keepRatio />
      <SelectToZoom
        disabled={props.zoomMode || props.disabled}
        keepRatio
        modifierKey="Control"
      />
    </>
  );
}
```

I will just rewrite my code to use a `if`.

But you maybe have a better idea.

**Comment by vallsv** [comment]
Here is my new implementation.

That's not working. I think the problem is somewhere else.

Basically `SelectToZoom` is not working without modifier.

```
function DefaultMouseInteraction(props: {
  zoomMode: boolean;
  panMode: boolean;
  disabled: boolean;
}) {
  console.log(props.panMode, props.zoomMode);
  if (props.disabled) {
    return <></>;
  }
  if (props.zoomMode) {
    <>
      <Pan modifierKey="Control" />
      <SelectToZoom keepRatio />
    </>;
  }
  return (
    <>
      <Pan />
      <SelectToZoom keepRatio modifierKey="Control" />
    </>
  );
}

```

**Comment by vallsv** [comment]
This sounds like to work
```
function DefaultMouseInteraction(props: {
  zoomMode: boolean;
  panMode: boolean;
  disabled: boolean;
}) {
  const panKeyModifierKey = !props.panMode ? 'Control' : undefined;
  const zoomKeyModifierKey = !props.zoomMode ? 'Control' : undefined;
  return (
    <>
      <Pan disabled={props.disabled} modifierKey={panKeyModifierKey} />
      <SelectToZoom
        disabled={props.disabled}
        keepRatio
        modifierKey={zoomKeyModifierKey}
      />
    </>
  );
}
```

**Comment by loichuder** [comment]
Yeah, this has probably to do with how we register interactions in the `Pan` and `SelectToZoom` components.

Glad you found a solution but I will keep the issue open. As you said, either it is a bug to be fixed or H5Web should throw a warning.

**Comment by axelboc** [comment]
In theory, only one `Pan` and one `SelectToZoom` component can be rendered at a given time. This is due to the `id` that we pass to the `useInteraction` hook internally in each interaction component. We could allow overriding this ID via a prop, but your third solution demonstrates perfectly why this is not needed. Enabling/disabling/configuring interaction components dynamically via props is the most efficient solution since the components are not unmounted/remounted when the props change.

However, you've indeed uncovered a couple of problems:

- Your first solution did not warn you about not using two interaction components with the same ID.
- Your second solution only renders one component of each type at a time, so in theory, it should have worked.

**Comment by vallsv** [comment]
But if i understand it well. i will not be able to define panning with middle click + panning with left click? at the same time.

**Comment by axelboc** [comment]
In the end, we went for allowing multiple buttons to be passed to `Pan` (#1149): 

```tsx
<Pan button={[MouseButton.Left, MouseButton.Middle]} />
```

There really doesn't seem to be a valid use case for using multiple `Pan` components at this point, so we've decided not to let the internal interaction ID be overridden. Don't hesitate to prove us wrong, though! :wink:
