### ISSUE TITLE
data sources for h5web/h5wasm

### ISSUE THREAD

**Issue by linupi** [silx-kit/h5web#1158]
I really like the service that is offered at https://h5web.panosc.eu/h5wasm and was wondering what are the main foreseen data sources if one looks at this as a service e.g. to provide links to visualize h5 files e.g. in a documentation. In a way I compare it to the [Jupyter notebook viewer](https://nbviewer.org/). I can clearly see two use-cases, but maybe there are more:

- provide a view for files on github (examples would be files provided by [orso](https://github.com/reflectivity/file_format/tree/master/nexus_formats) or [NeXus](https://github.com/reflectivity/file_format/tree/master/nexus_formats) )
- provide a view for files hosted on zenodo [(e.g. the h5 file in here)](https://zenodo.org/record/6497438 )

The question would be if you'd consider it as useful to have a more easy way of specifying the datafile the user would should look at than just providing a URL (something like the github intergration in the nbviewer) for certain data sources.

### Is your feature request related to a problem?
no 

### Requested solution or feature
a feature

### Alternatives you've considered
obviously on can the url directly but I am not sure if that is the best user experience for the content provider

**Comment by axelboc** [comment]
Hi @linupi, to avoid CORS issues with GitHub, the URL has to start with https://raw.githubusercontent.com/. Check out this repo for an example: https://github.com/oasys-esrf-kit/dabam2d

**Comment by linupi** [comment]
Thanks for the hint regarding https://raw.githubusercontent.com/. For zenodo I figured by now that there is also a way to circumvent the CORS issue by going through the api. E.g. for the [xrr_dataset.h5 in zenodo.6497438](https://zenodo.org/record/6497438)  the correct url would be
```
https://zenodo.org/api/files/b0bfa823-917d-4fe6-9a02-4396743a6037/xrr_dataset.h5
```
where the id in the url can be resolved through the zenodo api (e.g. https://zenodo.org/api/records/6497438 ) which is quite un-intuitive for the user. I guess this is why I'd really like to see the h5wasm service to cope with zenodo and github in a user-friendly way by converting to the correct urls internally.

**Comment by axelboc** [comment]
For a bit of context, https://h5web.panosc.eu/h5wasm is meant to just be a demo: a way for us to test the `H5WasmProvider` and to let people try the H5Web viewer on their own files to gather more valuable feedback. The whole demo app is continuously deployed from the `main` branch, so it can break easily and is definitely not production-ready.

Considering this, we are reluctant to add more features to https://h5web.panosc.eu/h5wasm at this point. Instead, we plan on developing a dedicated, production-ready service based on H5Wasm in a separate repo.

We'll definitely add the feature you suggest to this new, dedicated service. By the way, Binder actually has a good UI for this: https://mybinder.org/. We'll leave this issue open until we create the new repo, and then migrate the issue there.

**Comment by linupi** [comment]
Ok @axelboc, thanks for the context. After the announcement of @andygotz on the panosc mailing list regarding the https://h5web.panosc.eu/h5wasm ,I had the impression that it was meant as a real production service and not just a demo.

**Comment by axelboc** [comment]
Yeah, sorry for the confusion ^^

**Comment by loichuder** [comment]
The service is now available through the HDFGroup website: https://myhdf5.hdfgroup.org/
