### ISSUE TITLE
Add documenation how to provide url to h5wasm

### ISSUE THREAD

**Issue by linupi** [silx-kit/h5web#1159]
https://github.com/silx-kit/h5web/blob/487e6c7fe2062c1a75ba167e6d798066e5170c95/README.md?plain=1#L101

It would be nice to have an example like
```
https://h5web.panosc.eu/h5wasm?url=https%3A%2F%2Fwww.silx.org%2Fpub%2Fh5web%2Fwater_224.h5
```
 in the README.md

**Comment by loichuder** [comment]
Good point.

Perhaps we should instead only point to the [demo homepage](https://h5web.panosc.eu/) in the README.md to avoid maintaining two documentation sources. What do you think @axelboc ?
