### ISSUE TITLE
[Matrix] Allow other numeric styles than scientific notation

### ISSUE THREAD

**Issue by imikejackson** [silx-kit/h5web#1175]
### Is your feature request related to a problem?

No

### Requested solution or feature

Allow the display of the raw data in something other than scientific notation.

**Comment by loichuder** [comment]
Hello @imikejackson 

Thanks for bringing up the issue.

Would you mind elaborating on which cases the scientific notation is not adapted in your case ? 
Is it for integers ? Decimal numbers ? In the latter case, would you need to control the number of decimals ?
