### ISSUE TITLE
Possible "ignore" netCDF-4 fill value/missing values?

### ISSUE THREAD

**Issue by mathomp4** [silx-kit/h5web#1181]
### Is your feature request related to a problem?

So, I've been having fun with the the fun h5web vscode extension with my netCDF files, but today I encountered something that hadn't yet: missing values (aka fill values).

I made a quick little netCDF-Python script to make up a variable where the fill value is 1e15:
```bash
❯ ncdump -hsc test_miss.nc4
netcdf test_miss {
dimensions:
	nlocs = 1000 ;
variables:
	float nlocs(nlocs) ;
		nlocs:_Storage = "contiguous" ;
		nlocs:_Endianness = "little" ;
	float value(nlocs) ;
		value:_FillValue = 1.e+15f ;
		value:_Storage = "contiguous" ;
		value:_Endianness = "little" ;

// global attributes:
		:_NCProperties = "version=2,netcdf=4.8.1,hdf5=1.12.1" ;
		:_SuperblockVersion = 2 ;
		:_IsNetcdf4 = 1 ;
		:_Format = "netCDF-4" ;
}
```
but in this script, I didn't fill every point in the `value` variable, just some of them (randomly). When you do this, the output from `ncdump` looks like:

```bash
❯ ncdump -v value test_miss.nc4 | head -12
netcdf test_miss {
dimensions:
	nlocs = 1000 ;
variables:
	float nlocs(nlocs) ;
	float value(nlocs) ;
		value:_FillValue = 1.e+15f ;
data:

 value = 8.252128, _, 3.278462, 1.717357, 3.64509, 5.895305, 6.32355,
    9.360811, _, _, _, 1.007396, 4.095286, _, _, _, _, _, _, _, _, 9.35124,
    _, _, _, _, _, _, _, _, _, _, 6.430166, _, 5.538579, 4.860384, _,
```

`ncdump` sees we have a `_FillValue` set, and shows them as "missing".

But since the h5web extension doesn't know that (since I'm guessing netCDF-4 doesn't define the fill value as an HDF5 fill value...if that exists?), then you get this when you view it:

<img width="864" alt="Screen Shot 2022-08-01 at 1 19 56 PM" src="https://user-images.githubusercontent.com/2982494/182206349-c765ec83-58c2-4a2c-9199-61393eba682d.png">

Now, if you turn on points and use a log scale for y:

<img width="864" alt="Screen Shot 2022-08-01 at 1 20 07 PM" src="https://user-images.githubusercontent.com/2982494/182206376-b6d4848b-219c-416e-a580-4f3f99e546d2.png">

You can see all the "real data" at the bottom, but since the code assumes all code is valuable, you get the all the points at the 1e15 gumming things up.

I also see this in a 2D array our climate model uses:

<img width="864" alt="Screen Shot 2022-08-01 at 1 20 52 PM" src="https://user-images.githubusercontent.com/2982494/182206491-ccefa545-1ddf-499b-9a2a-a5c37c57fe14.png">

This is at the 1000 mbar pressure level and since much of the is above that, you get these yellow bands. Of course, with 2D variables, I can edit the range it looks like:

<img width="864" alt="Screen Shot 2022-08-01 at 1 35 00 PM" src="https://user-images.githubusercontent.com/2982494/182208734-18246be6-e7d3-4350-824d-677fcc039244.png">

So I can see some features in the real data. But as far as I can tell, I can't seem to restrict the axes in a 1d variable?

### Requested solution or feature

It would be nice to either have a toggle/button where you could treat any netCDF default fill value as "missing" which would be...transparent? I'm not sure.

### Alternatives you've considered

Not much. I mean, this might not be possible. If it isn't (since it might be a feature of netCDF), maybe a way to restrict the axes?

**Comment by loichuder** [comment]
Hello @mathomp4, thanks for the report !

If I understand correctly, you would want that values with fill value to be treated somehow as "invalid". This is unrelated to the format as you would get the same behaviour with HDF5 fill values.

I would argue that setting a fill value is to tell: _I want to have a fallback for unset values_. In my opinion, this is different from saying: _I want unset values to be invalid_. 

It would be difficult in my opinion to implement heuristics that would able to distinguish between these two scenarios. For example, you may use `1e15` as a personal convention for invalid values but someone else might use another value. Or, even, someone else might expect to keep the fill value and not treat it as invalid.

If you have writing access to your file (and if netCDF allows it), I would propose you to use `NaN` instead to designate invalid values. This has the advantage to be clearer and it would solve your plot problems as when using datasets with `NaN`:
- Axis scales are computed only from the valid values
- Parts with `NaN` appear as transparent in the **Heatmap**

Do not hesitate to elaborate on your issue if I misunderstood something. I will leave the issue open for now.

**Comment by axelboc** [comment]
A solution might be to implement an eyedropper tool of sorts. Below is Firefox' eyedropper for context, but the idea would be to simply show a cross-hair cursor instead of the default cursor and keep the popup visible so the user can see the value under the cursor. Then, when the user clicks, the value under the cursor gets selected and passed to the shader as a uniform to be checked as part of the `if (isnan(value) || isinf(value) || !isSupported(value)) { gl_FragColor = nanColor; }` condition.

![image](https://user-images.githubusercontent.com/2936402/196876970-e0867939-87d4-419a-9050-f7f5c6d6757e.png)

This seems like a simple-enough solution as long as we **don't** try to display the selected value in the toolbar, or let people edit the value manually, or allow using the value as a low-pass/high-pass filter, etc. Just a simple, single-value state that is not persisted and used in the shader for an exact equality check.

**Comment by axelboc** [comment]
Showing a cross-hair cursor on the line visualization wouldn't make quite as much sense, so we'd have to think of a better UI, but the concept still works: you click to select a value and it then gets treated as a `NaN` value. If the "fill" value is very close to real values, the user can of course zoom in.

**Comment by axelboc** [comment]
Note that the domain computation will also be impacted by this feature: the selected value will have to be ignored when looping through the values to find the min/max. This should not impact performance, though.

**Comment by loichuder** [comment]
@mathomp4 A recent issue related to your problem popped up and made me think that we could revisit this.

Could you provide us with a netCDF file with such a fill value (ex: the file `test_miss.nc4` you generated) ?

Thanks !

**Comment by mathomp4** [comment]
@loichuder I took a look around and I still have the file! Go me...for not cleaning up my computer 😄 


Please find it attached. I gzip'ed it because of GitHub rules on file type/extensions.

[test_miss.nc4.gz](https://github.com/silx-kit/h5web/files/10920424/test_miss.nc4.gz)

**Comment by loichuder** [comment]
Great ! Thanks for the quick reply, I will have a look at this.

**Comment by loichuder** [comment]
@mathomp4 Is this the plot you would expect when the fill value is taken into account?

![image](https://user-images.githubusercontent.com/42204205/224020302-8abfcea2-0020-47c5-bb37-325a7d4cc2a3.png)

With points:

![image](https://user-images.githubusercontent.com/42204205/224020397-c2a1a9ca-5e52-433f-9bc4-be2703395638.png)

**Comment by mathomp4** [comment]
@loichuder I think so. If I correctly read the python script I made to generate it, it should be 60% "fill value" and the other 40% `np.random.uniform(10.0)`.

And those look to be between 0 and 10!
