### ISSUE TITLE
ATL03 can't be opened.

### ISSUE THREAD

**Issue by hyoklee** [silx-kit/h5web#1197]
### Describe the bug

H5Web doesn't show anything after opening this file:

https://gamma.hdfgroup.org/ftp/pub/outgoing/NASAHDF/ATL03_20181027235521_04480111_004_01.h5

### To Reproduce

1. Download file.
2. Open it.

### Expected behaviour

It should show groups like HDFView.

### Screenshots

![ATL03_h5web_bug](https://user-images.githubusercontent.com/4994401/187706193-4aa6e64b-87d8-4e67-af2b-cf5c9dfdc487.png)

### Context

- OS: Win 10
- Browser:  VS Code
- Version: Version: 1.70.2 (user setup)
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:35:13.448Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044
- H5Web context: VS Code extension

**Comment by bmaranville** [comment]
My first guess is that the address of some piece of ```/ds_surf_type``` is greater than what is available in the 32-bit build of libhdf5 used in h5wasm (the file is just a tiny bit bigger than the max file size in a 32-bit filesystem).

It looks like an overflow of address space is happening on read (see error messages from load):
```
  #016: /home/brian/dev/libhdf5-wasm/wasm_build/1_12_1/_deps/hdf5-src/src/H5FDint.c line 189 in H5FD_read(): driver read request failed [hdf5_util.js:9:3156577](https://h5web.panosc.eu/node_modules/.pnpm/h5wasm@0.4.4/node_modules/h5wasm/dist/esm/hdf5_util.js)
    major: Virtual File Layer [hdf5_util.js:9:3156577](https://h5web.panosc.eu/node_modules/.pnpm/h5wasm@0.4.4/node_modules/h5wasm/dist/esm/hdf5_util.js)
    minor: Read failed [hdf5_util.js:9:3156577](https://h5web.panosc.eu/node_modules/.pnpm/h5wasm@0.4.4/node_modules/h5wasm/dist/esm/hdf5_util.js)
  #017: /home/brian/dev/libhdf5-wasm/wasm_build/1_12_1/_deps/hdf5-src/src/H5FDsec2.c line 761 in H5FD__sec2_read(): file read failed: time = Thu Sep  1 10:22:47 2022 [hdf5_util.js:9:3156577](https://h5web.panosc.eu/node_modules/.pnpm/h5wasm@0.4.4/node_modules/h5wasm/dist/esm/hdf5_util.js)
, filename = 'ATL03_20181027235521_04480111_004_01.h5', file descriptor = 3, errno = 28, error message = 'Invalid argument', buf = 0x5cff30, total read size = 1064, bytes this sub-read = 1064, bytes actually read = 18446744073709551615, offset = 0 [hdf5_util.js:9:3156577](https://h5web.panosc.eu/node_modules/.pnpm/h5wasm@0.4.4/node_modules/h5wasm/dist/esm/hdf5_util.js)
    major: Low-level I/O [hdf5_util.js:9:3156577](https://h5web.panosc.eu/node_modules/.pnpm/h5wasm@0.4.4/node_modules/h5wasm/dist/esm/hdf5_util.js)
    minor: Read failed
```

**Comment by loichuder** [comment]
The file can be opened in the current H5Web demo: https://h5web.panosc.eu/h5wasm (h5wasm v0.4.6).

I think an update of h5wasm in the VSCode extension should fix this (currently at v0.4.4).

**Comment by loichuder** [comment]
After further investigation, this is a limitation of VSCode that prevents the buffer containing the file contents to go over a certain size (seems to be around 2Go). Removing some datasets reduces the file size allowing it to be read by the extension.

Unfortunately, given the issue arises at VSCode level, I fear there is not much we can do except documenting the limitation...

**Comment by hyoklee** [comment]
@loichuder Thank you for investigating the issue. I hope MS VSCode can resolve the issue soon and we can try it again.

**Comment by loichuder** [comment]
Having streamed reading in H5Wasm could also be a way to fix it.

Anyway, thanks again for the report. The next version of the extension will show an error when the file is too big.

**Comment by bmaranville** [comment]
If you have a webserver that supports 
- range requests and
- CORS (e.g. "Access-Control-Allow-Origin: *")

Then you can try out the on-demand piecewise file loader at https://github.com/bmaranville/lazyFileLRU, which has a demo for loading a remote file with h5wasm.
This FS implementation will not run into the same buffer size limitation.
