### ISSUE TITLE
Persistence of `SILX_style` options

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#1199]
### Is your feature request related to a problem?

When we select a dataset with a `SILX_style` attribute (e.g. `/nexus_entry/log_spectrum`) and then another dataset without (e.g. `/nexus_entry/spectrum_with_aux`), the axes scales of the first dataset are persisted.

I've always found this behaviour to be quite annoying. I understand that the point of `SILX_style` is to override any persisted configuration but the fact that the `SILX_style` config itself gets persisted doesn't feel right, since the user doesn't explicitly change the configuration from the toolbar.

I'm reporting this now, since we risk running into a similar issue in #1198 when reviewing the way we persist the `layout` option. If we decide to persist the computed `layout` for the current dataset whenever it differs from the saved `layout`, then we end up in the same situation as above with a configuration option that gets persisted without the user's knowledge/say so.

### Requested solution or feature

The `SILX_style` overrides could simply be applied to the current visualization without being persisted.

**Comment by axelboc** [comment]
This is more challenging that I initially thought in our current architecture. The difficulty comes from the fact that we want the "preferred" scale type (for instance) to apply only until the user decides otherwise. So if the `SILX_style` says the preferred scale type is `log`, the visualization should use `log` by default, but as soon as the user changes the scale type manually, the preferred scale type should be ignored.

### Solution 1: `useState`

```tsx
// In mapped vis (code and variable names simplified for clarity)
const { preferredValue } = props;
const storedValue = useConfig(state => state.value);

const [hasChanged, toggleChanged] = useToggle(false);

// Where we need the value (in the mapped vis and the toolbar)
hasChanged ? storedValue : preferredValue;

// Where we need to change the stored value (in the toolbar)
const setValue= useConfig(state => state.setValue);
setValue(newValue);
toggleChanged();
```

`useToggle` and ternary could be abstracted into custom hook - e.g. `useUntilChanged`, and a monkey-patched `setValue` could be also passed down to the toolbar, but it still leaves a lot of things to wire up, variables to rename, long variable names, etc. And all of this wiring up has to be duplicated in other mapped vis components and for each value (x/y/colormap scale types).

### Solution 2: more props in store

Currently, we update the store via `useEffect` from the toolbar with the values parsed from `SILX_style`. Instead of setting the keys that are persisted (e.g. `scaleType`), we could set other keys that would not persisted (e.g. `preferredXcaleType`). We could then unset them when the persisted key is set.

```tsx
// Heatmap config
setScaleType: (scaleType: ScaleType) => {
  set(() => ({ scaleType, preferredScaleType: undefined }));
},
setPreferredScaleType: (preferredScaleType: ScaleType | undefined) => {
  set(() => ({ preferredScaleType }));
},

// Heatmap toolbar
useEffect(() => {
  setPreferredScaleType(preferredScaleType); // would need to be optimised to avoid re-rendering when not needed, while still resetting the `preferredScaleType` properly
}, []);

// Mapped vis
preferredScaleType || scaleType
```

The downsides of this solution are:

- more clutter in the config store (especially in the line vis config store);
- asynchronous store updates via `useEffect`, which may cause issues (risk of not resetting `preferredScaleType` properly or using a stale value from another dataset.

### Solution 3: pass config down as prop from container

Perhaps solution 1 could work better if the config was passed down as prop from the vis container. The container would call the store's hook (e.g. `useLineConfig`), which would hold the `useState` from solution 1 and return the stored vs preferred value accordingly.

**Comment by loichuder** [comment]
Thanks for the summary of your investigations!

As discussed earlier, solution 3 seems indeed the cleanest to me if we manage to trigger a re-render without too much trouble.

**Comment by axelboc** [comment]
As discussed, we should maybe reconsider storing our vis configs in global zustand states. 

The configs should perhaps be retrieved from local storage every time a new dataset is selected, overridden with NeXus preferences if any, and stored in local state. When the user then changes a config option, only that option should be persisted so as to never persist NeXus preferences.
