### ISSUE TITLE
Parsing Nexus signal when it contains the dataset path instead of the name

### ISSUE THREAD

**Issue by kif** [silx-kit/h5web#1212]
### Describe the bug

When opening files with this default NXdata, I got this error message `Expected "q2Rg2I/I0" signal entity to exist`
The bug comes from the "/" in the dataset name...

### To Reproduce

Only files under embargo are exhibiting this for now, I will keep you informed when such files are pubilcly available.
For now, see file
data/visitor/mx2447/bm29/20220927/LILRB3_A29_hplc/LILRB3_A29_hplc_sample_LILRB3_A29/processed/hplc/sample_LILRB3_A29000_hplc.h5
with silx and h5web, especially the NXdata  at /entry_0000/5_SEC_fractions/454-503/3_dimensionless_Kratky_plot
The NXdata attributes contain:
@signal="q2Rg2I/I0"
### Expected behaviour

This is what silx sees and it looks correct:

### Screenshots

![image](https://user-images.githubusercontent.com/1018880/192562117-215700f9-a563-43a7-b793-d01b1fd315c8.png)

### Context

- OS: linux
- Browser: firwfox
- Version: 91.13.0esr
- H5Web context:  @h5web/app

**Comment by axelboc** [comment]
So does the `signal` attribute contain a path to a dataset instead of a dataset name? Or does the dataset name include a slash and silx displays it as a dataset inside a group regardless?

**Comment by loichuder** [comment]
The former: The signal attribute contains a path to a dataset instead of a dataset name

**Comment by axelboc** [comment]
Perhaps @woutdenolf might have some insight on this?

**Comment by woutdenolf** [comment]
Indeed, having a path in `@signal` is not allowed as far as I understand. This also applies to @auxiliary_signals and @axes

> @signal: (optional) [NX_CHAR](https://manual.nexusformat.org/nxdl-types.html#nx-char)
>  Declares which NeXus field is the default. The value is the name of the NeXus field to be plotted. (The value [names](https://manual.nexusformat.org/datarules.html#validitemname) an existing child of this group. The child group must itself be a NeXus group.)

So `The value names an existing child of this group` is pretty clear: it must be a name of a dataset under the NXdata group.

Perhaps the sentence `The child group must itself be a NeXus group` causes confusion. I have no idea what this means btw.

**Comment by axelboc** [comment]
Closing as per discussions. Let us know what you think, @kif. 😉
