### ISSUE TITLE
Invalid package.json "type" field on npm install

### ISSUE THREAD

**Issue by imathews** [silx-kit/h5web#1219]
### Describe the bug
When installing `@h5web/app` and `@h5web/wasm` (`@6.3.0`), the package.json file for the installed packages in `node_modules` contains an invalid `"type": ""` field. The `type` in `package.json` should be one of `commonjs`, `module`. This is specifically happening for @h5web/lib, @h5web/app, @h5web/h5wasm.

I can see that the package.json in this repo doesn't have any `"type"` field, so I imagine it must be getting added during a build step.

The incorrect field creates distracting warnings on certain build tools, such as esbuild (see below). I imagine this might effect tree shaking and other module resolution behavior for these tools as well (though FWIW, h5web is working smoothly despite these warnings).
```
▲ [WARNING] "" is not a valid value for the "type" field [package.json]

    node_modules/@h5web/app/package.json:11:10:
      11 │   "type": "",
         ╵           ~~

  The "type" field must be set to either "commonjs" or "module".
```

### To Reproduce

`npm install @h5web/app`

### Expected behaviour

The "type" field in package.json I believe should be set to `"module"` for this library

### Context

- OS: macos
- NPM version: 8.5.5
- Version: 6.3.0
- H5Web context:  @h5web/lib, @h5web/app, @h5web/h5wasm

**Comment by axelboc** [comment]
Hi @imathews, thanks for the report.

Each package has its own `package.json` with [`"type": "module"`](https://github.com/silx-kit/h5web/blob/main/packages/app/package.json#L11):  for development. We override this to `"type": ""` on publish via [pnpm](https://pnpm.io/)'s [`"publishConfig"` object](https://github.com/silx-kit/h5web/blob/main/packages/app/package.json#L18).

At first, we used to publish with `"type": "module"`, but then CRA v5 / webpack v5 came around and we had some issues. I can't quite recall what they were -- maybe something with missing `js` extensions in import paths of dependencies... Yeah looks like it: https://github.com/silx-kit/h5web/pull/1000. But then CRA did not like `"commonjs"` either for some reason and we removed it: https://github.com/silx-kit/h5web/commit/50c9ef8e8bebeace2ea54b7c925a54c69271542a.

I'll investigate again if the original issue can be resolved another way.

**Comment by imathews** [comment]
Thanks for the update @axelboc - all makes sense. I'm not particularly familiar with pnpm, though I wonder if there's a way to just remove the `type` field entirely from the distributed package.json... perhaps that would be enough to make all these tools happy? But agree if there's a way to sort #1000 in another way, that probably seems like the best path forward.

**Comment by imathews** [comment]
Just tried this out — this release seems to do the trick (no more warnings on build, and otherwise h5web continues to work great). Thanks @axelboc!

**Comment by axelboc** [comment]
Great to hear! 🎉
