### ISSUE TITLE
[Heatmap] Tooltip guides

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#125]
@loichuder you had suggested this in the chat a while back: adding horizontal and vertical guides to the tooltip. Here's a mockup:

![image](https://user-images.githubusercontent.com/2936402/81292105-4e6eb500-906b-11ea-8eb9-688a34363501.png)

**Comment by loichuder** [comment]
Adding only the vertical one would work for the LineVis.

Here is an example from VX's gallery: https://vx-demo.now.sh/areas
