### ISSUE TITLE
Responsive breadcrumbs

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#127]
![image](https://user-images.githubusercontent.com/2936402/81296368-0f902d80-9072-11ea-9355-11a26ecbfeb4.png)

We could just [hide the parent crumbs](https://codepen.io/jyoakum-swx/pen/meRYjd) for now, or [crop them with ellipsis](https://codepen.io/JEETPAL/pen/qNKWRy). If we decide to make them clickable we'd have to turn them into a sort of [drop-down menu](https://codepen.io/mejiaj/pen/Kdwma) or make them [expandable](https://codepen.io/fraddski/pen/azjwev).

**Comment by loichuder** [comment]
Hiding the parent crumbs sounds good to me
