### ISSUE TITLE
[Histogram] The mouse interaction is not centered to the line

### ISSUE THREAD

**Issue by vallsv** [silx-kit/h5web#1277]
### Describe the bug

The interaction zone over the histogram ranges are not centred.

It's maybe easer to explain in a front of a computer.

Basically on my computer the interaction looks like the left side of this diagram.

I would expect it to feel like the right. Because the right is right.
Else it's really surprising, and depending on the side you want to grab the line, you feel like it's just not interactive.

![Screenshot from 2022-11-10 17-15-55](https://user-images.githubusercontent.com/7579321/201149820-9c072a92-48a9-4cef-ab93-1c1b518d7a74.png)

**Comment by loichuder** [comment]
That could indeed feel unnatural. I will get at it.
