### ISSUE TITLE
Explicit caching step in CI

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#1315]
> When the `pnpm-lock.yaml` changes and we push code to the repo, if the `lint` job succeeds but not the `e2e`, we end up with a cache for the pnpm store but not the Cypress binaries. When that happens, on subsequent pushes, the `e2e` job always fails because it can never find the binaries, and the binaries never get cached. Only way to resolve is to change `pnpm-lock.yaml`, push and hope that the `e2e` passes.

> To resolve this, I now cache the Cypress binaries in every job. This is not ideal. I've opened an issue in `actions/setup-node` to solve this more elegantly: https://github.com/actions/setup-node/issues/638

_Originally posted by @axelboc in https://github.com/silx-kit/h5web/pull/1312#discussion_r1039599412_
      
Since `actions/setup-node` closed my issue, I'll add a separate caching step.

**Comment by loichuder** [comment]
Fixed by #1319
