### ISSUE TITLE
Problem with NeXus data

### ISSUE THREAD

**Issue by jarrah42** [silx-kit/h5web#1350]
### Describe the Bug

NeXus data supports storing axes as either bin centers or bin boundaries, which means that an axis can have one more bin boundary than bins. When viewing this type of file, h5web will display the error `Expected abscissa array to have length N instead of N+1`

### To Reproduce

1.  Unzip the attached file [chopper.nxs.zip](https://github.com/silx-kit/h5web/files/10436650/chopper.nxs.zip)
2. Upload the file using `H5Wasm`
3. Click on `NX Line`
4. The error message should be visible

### Expected behaviour

NeXpy (https://github.com/nexpy) is able to display these files correctly.

### Screenshots

<img width="768" alt="Screen Shot 2023-01-17 at 10 42 47 AM" src="https://user-images.githubusercontent.com/6130694/212943483-2bd4c747-977c-4b69-bd31-eb33f2c09d01.png">

**Comment by axelboc** [comment]
Seems that this is a regression. Thanks for the report!
