### ISSUE TITLE
[HeatmapMesh] NaN, +inf, -inf are all displayed the same way

### ISSUE THREAD

**Issue by vallsv** [silx-kit/h5web#1372]
### Describe the bug

+inf, -inf, nan are displayed the same way from `HeatmapMesh`.

Tested with `float16`, but it's probably the same with `float32`.

### Expected behaviour

We would expect as default behaviour:

- NaN -> transparent for 
- +inf -> highest color of the lut
- -inf -> lowest color of the lut

**Comment by vallsv** [comment]
FYI @t20100

**Comment by vallsv** [comment]
According to @t20100 there is also a typo with the nanColor

```
        if (isnan(value) || isinf(value) || !isSupported(value)) {
          gl_FragColor = nanColor;
        } else {

const vec4 nanColor = vec4(255, 255, 255, 1);
```

Which should be clamped `1, 1, 1, 1`

**Comment by loichuder** [comment]
Sounds reasonable to me. I don't have really strong opinions on how these should be displayed.

**Comment by axelboc** [comment]
I'm reluctant to change the current behaviour in the viewer, as we haven't had any feedback suggesting to change it. On the contrary, in #1181, the idea is to treat a specific, high value (read from HDF5) as "fill value" by ignoring it from the domain computation and hiding it completely from the visualization (i.e. transparent on heatmap vis; removed on line vis). In a way, we're treating `+/-Infinity` as the H5Web viewer's **default** fill value.

Of course, we could add a control in the toolbar to change the colors used for fill values but someone would have to make a case for this feature.

For now, I suggest we make the requested behaviour configurable in `HeatmapMesh`, perhaps with a prop called `fillColor: 'transparent' | 'minmax' | string`.

**Comment by vallsv** [comment]
If you want extra options, please take a look at matplotlib API before creating new stuffs https://matplotlib.org/stable/api/_as_gen/matplotlib.colors.Colormap.html `bad`/`over`/`under`

**Comment by axelboc** [comment]
It was just a suggestion, that's why we're discussing it in an issue. 😊 I'm not familiar with matplotlib's API, so always happy to be pointed to the relevant information, thanks!

**Comment by t20100** [comment]
I'd also expect as default behaviour to have -/+Inf displayed with colors of the extrema of the colormap as any other under/over value (those are value numbers), and NaN (as well as value not supported by the used scale) not being displayed, and then add needed props to configure this for what is needed.

The `bad(or nan)/over/under` looks the most generic way to do it. I would at least separate the handling of NaN (with e.g. `nanColor` or `badColor`) from +/-Inf and over/under values:

- For the "bad" values, I see interest in choosing between a dedicated color and "transparent" (could even be using `discard` in the shader) to display what's behind it (possible future use case of multiple tilings displayed one on top of the other at different resolutions but not there yet).
- For over/under, I'm not sure what configuration is exactly needed:
  - Separate +/-Inf from over/under? Probably not, matplotlib doesn't.
  - Separate over from under or configure both at once? For which need?

**Comment by loichuder** [comment]
> Separate +/-Inf from over/under? Probably not, matplotlib doesn't.

This means that the current treatment cannot be reproduced since +/-Inf color are currenlty different from the regular over/under values:

| | Current | Future |
| - | ------| ----- |
| `NaN` | `white` | `transparent` |
| `+/- Inf` | `white` | `over/under` color |
| Regular over/under | `over/under` color | `over/under` color |

I am not against it. Just stating things clearly.
