### ISSUE TITLE
Scatterplot

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#141]
If I'm not mistaken, this visualization will only be useful once we start supporting Nexus. I'm opening an epic nonetheless for reference and any preliminary discussion.

**Comment by loichuder** [comment]
Could you put explicitly what do you mean by "scatterplot" ?

**Comment by axelboc** [comment]
Something like this, where each point represents a country:

![image](https://user-images.githubusercontent.com/2936402/82324202-8d8cf680-99d9-11ea-9a92-6486d81fd7f4.png)

Each data point is positioned according to two values, in this case "life expectancy" and "GDP per capita". Once positioned, a point can be represented differently (size, shape, colour, etc.) based on additional values, in this case the colour of each point represents the country's continent.

In our case, this is different from a line plot in the sense that both axis are data axis, which cannot happen without Nexus support, I think.

**Comment by loichuder** [comment]
Request from @vallsv

Could be point-based:
![image](https://user-images.githubusercontent.com/42204205/144569886-761df752-4060-4606-9876-a30aa4286168.png)

Or using a regular grid:
![image](https://user-images.githubusercontent.com/42204205/144570049-fca33b17-289c-4cdd-81f2-c5ef874c1a89.png)

**Comment by vallsv** [comment]
The data format is
```
x: [...]
y: [...]
value: [...]
```

The solid rendering is used to be called hitmap i think (on silx it's histogram2D)

For solid, at one point we will probably also have to deal with meta like x/y-pixel-size, x/y-min, x/y-max to properly place the grid on the axis. See https://github.com/silx-kit/silx/blob/058b479031b450846c792aa91c63a161c9f8b778/src/silx/gui/plot/items/core.py#L1181 , but for now displaying anything would be very helpful.

**Comment by loichuder** [comment]
First implementation in #913

**Comment by loichuder** [comment]
After discussion with @t20100, we could have a NXScatter if a NXData group has
- a 1D `signal`
- two 1D `axes`
- `signal` and `axes` datasets of the same length

This would be a first basic support

**Comment by axelboc** [comment]
I feel like this issue is now resolved:

- We have `ScatterVis`, which comes with a full-featured API, which is pretty much in line with other visualizations (axes scale types, `invertColorMap`, `interactions`, etc.)
- We also have `NxScatter`, which brings scatter visualizations to `@h5web/app`.

The solid/grid-based scatter plot is now covered by #1061. Feel free to re-open if needed.
