### ISSUE TITLE
Legend for LineVis, HeatmapVis, MatrixVis

### ISSUE THREAD

**Issue by cmmngr** [silx-kit/h5web#1426]
### Is your feature request related to a problem?

For multi-dimensional data sets, it is not obvious what the parameters labelled D0, D1, D2,... are (e.g. which physical quantities are behind D0, D1, ...), that can be selected for the x- and y-axes in MatrixVis, LineVis and HeatmapVis plots.

### Requested solution or feature

It would help to have a small legend which defines what D0, D1, D2, ... are (depending on whatever names are provided by the user, for example, D0: energy, D1: intensity etc.) if there is more than one Di.

**Comment by axelboc** [comment]
This relates to supporting HDF5 scales, if I'm not mistaken? https://github.com/silx-kit/h5web/issues/1313

**Comment by cmmngr** [comment]
> 

Yes, exactly. However, in NeXus files, where axes names and attributes are provided, these names for D0, D1, ... could be shown in a legend or when hovering over the D0, D1, ... icons.
