### ISSUE TITLE
How to automatically plot multiple datasets (overlay)

### ISSUE THREAD

**Issue by bmaranville** [silx-kit/h5web#1447]
### Is your feature request related to a problem?

I'm not sure if this is something covered by the NeXus spec or not, but for polarized datasets, where an NXEntry is defined for each polarization state (multiple entries in the same file), I would like to have the default plot show all the polarizations simultaneously.

### Requested solution or feature

A way to specify multiple default datasets to be shown through NeXus metadata, that is used by H5Web to show the default plot

**Comment by bmaranville** [comment]
Thanks - I hadn't noticed the documentation on `auxiliary_signals` before.  That's very helpful!

**Comment by loichuder** [comment]
> I don't know if your visualisation need can be achieved without soft links

I think not. NeXus works in the top-down fashion: you follow attributes from the parent to the child so that your `auxiliary_signals` must be children of the NXdata group you want to display. So using absolute paths doesn't cut it.

**Comment by t20100** [comment]
> I don't know if your visualisation need can be achieved without soft links

I also think not.

Looking at the [NXData spec](https://manual.nexusformat.org/classes/base_classes/NXdata.html), it is explicit only for the `@signal`:
> The value [names](https://manual.nexusformat.org/datarules.html#validitemname) an existing child of this group
Nothing is said for `@auxiliary_signals` and `@axes`, but I'd expect all of them to be consistent...
