### ISSUE TITLE
Matrix row-col index

### ISSUE THREAD

**Issue by LogWell** [silx-kit/h5web#1450]
When viewing matrix elements, it is more convenient to use the fixed display index of rows and columns

![image](https://github.com/silx-kit/h5web/assets/34391447/745019ec-870b-49d9-b611-67a451b29aa8)

**Comment by loichuder** [comment]
You mean having the index row and column always displayed ?

You can click on `Freeze indices` in the top bar to achieve this:

![image](https://github.com/silx-kit/h5web/assets/42204205/0d8b273b-5993-49d2-a060-9daa5d28c48d)
