### ISSUE TITLE
encode and preview jpg / png image

### ISSUE THREAD

**Issue by LogWell** [silx-kit/h5web#1452]
For common jpg and png formats, encoding them before saving will reduce the file size, but at this time, the image cannot be previewed because they are encoded into arrays. Have you considered supporting image preview with encoding?

```
import numpy as np
import h5py
import cv2

path_png = "image.png"
img = cv2.imread(path_png, -1)

with h5py.File(path_png[:-4] + "_v1.h5", 'w') as h5f:
    h5f.create_dataset('img', data=img)

with h5py.File(path_png[:-4] + "_v2.h5", 'w') as h5f:
    result, img_png = cv2.imencode('.png', img)
    img_png = np.asarray(bytearray(img_png), dtype="uint8")
    h5f.create_dataset('img', data=img_png)

with h5py.File(path_png[:-4] + "_v2.h5", 'r') as h5f:
    img_png = h5f['img'][:]
    img_png = cv2.imdecode(img_png, cv2.IMREAD_COLOR)
    print("img_png:", img_png.shape)
```

![image](https://github.com/silx-kit/h5web/assets/34391447/26b5ce6f-904a-4d93-8a5f-f7face14049e)

**Comment by vasole** [comment]
In principle RGB and RGBA images should be supported. 

![image](https://github.com/silx-kit/h5web/assets/5636251/d603f038-2976-46b2-ac52-5fa8f65d0210)

They could be encoded using an HDF5 pluging filter to achieve the compression goal.

There are developments going on to support JPEG-2000 as an HDF5 filter, but they are not ready yet.

From the list of filters available, we already support FCIDECOMP (JPEG-LS) but I do not know if it is of any use to you

https://portal.hdfgroup.org/display/support/Registered+Filter+Plugins

@t20100 had a branch supporting JPEG as an HDF5 filter, but it was not easy to provide it as a multiplatform option.
