### ISSUE TITLE
Save image as...

### ISSUE THREAD

**Issue by LogWell** [silx-kit/h5web#1453]
Preview:
![image](https://github.com/silx-kit/h5web/assets/34391447/9b862dad-6bf2-455f-8c29-b2b8dfaaf5f0)

The saved image is a preview.
![image](https://github.com/silx-kit/h5web/assets/34391447/2d62260b-f31c-476e-955a-a756069c3ed5)

How to export raw images? Can you add an export/save button?

**Comment by loichuder** [comment]
For a while, you could save images _under the resolution they are displayed_, using the browser contextual `Save Image` or the `Snapshot` button for the Heatmap (see https://github.com/silx-kit/h5web/issues/95).

But apparently, this does not work anymore as I always get blank images.
