### ISSUE TITLE
[Dimension mapper] Basic view for 2D datasets

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#148]
This is part of epics #73 and #65.

![axis-dim-mapping](https://user-images.githubusercontent.com/2936402/82641374-8994ea80-9c0c-11ea-8751-1ba48cb9914d.png)

The goal of this issue is to visualize the dimensions currently assigned to `x` and `y` for a 3D dataset, or just `x` for a 2D dataset, and to set up some of the architecture in the code, as discussed:

- Add a hard-coded "mapping" object in `DatasetVisualizer` that declares the dimension assigned to `x` (i.e. `0`).
- Create a `DimensionMapper` component -- a basic vertical bar showing the dimension assigned to `x` (we may also need a component to control the visibility of the mapper based on the metadata of the selected dataset).
- Create a `VisProvider` that wraps `ActiveVis`, computes the correct `dims` and `data` for the given dataset and mapping object, and provides them to its children through a `VisContext`.
- Test that the mapper appears when it needs to and shows the correct axis/dimensions for 2D datasets.

**Comment by loichuder** [comment]
First step in #156

**Comment by loichuder** [comment]
Functional in #160
