### ISSUE TITLE
wasm function signature contains illegal type

### ISSUE THREAD

**Issue by prjemian** [silx-kit/h5web#1483]
### Describe the bug

H5Web failed to open HDF5 file in VSCode.  Reported the message in the issue title.

### To Reproduce

* RHEL9 OS
* Deleted all `~/.vscode*` and ~/.config/Code/`
* start `code`  # 1.52.1, ea3859d4ba2f3e577a159bc91e3074c5d85c0523, x64
* Install H5Web extension (0.0.9)
* double-click `20230823-160940-S00159-a5fc9df.hdf` file

Example data file enclosed in ZIP file:

[20230823-160940-S00159-a5fc9df.zip](https://github.com/silx-kit/h5web/files/12456116/20230823-160940-S00159-a5fc9df.zip)

### Expected behaviour

A view of the data in the file similar to this NeXpy view of the same data:
![image](https://github.com/silx-kit/h5web/assets/2279984/37870f31-ae75-448b-9c29-c21c1afe0829)

### Screenshots

![image](https://github.com/silx-kit/h5web/assets/2279984/dc40db3a-3540-495e-8aaf-70695909c726)

### Context

see above

**Comment by axelboc** [comment]
Hi @prjemian, I'm unable to reproduce this issue in VS Code 1.81.1:

![image](https://github.com/silx-kit/h5web/assets/2936402/d1b97efb-0989-4c06-bc5d-31801038400d)

The file also opens fine in https://myhdf5.hdfgroup.org, which also uses `h5wasm` under the hood.

Are you able to upgrade your installation of VS Code, by any chance?

**Comment by axelboc** [comment]
If you're able to pinpoint on which version of VS Code the error no longer occurs, I can update the [minimum version in `package.json`](https://github.com/silx-kit/vscode-h5web/blob/main/package.json#L29) ... or investigate a bit more what caused the issue in earlier version if backwards-compatibility is a strong need for you.

**Comment by prjemian** [comment]
Found the root cause: version of VSCode (on APS account) was too old.  Removed that version from the linux PATH, which then exposed the current version.  H5Web works as expected now.
