### ISSUE TITLE
Need H5Web to support plot True/False and Enum signals

### ISSUE THREAD

**Issue by Yayanzjg** [silx-kit/h5web#1498]
### Requested solution or feature

I am dealing with many signals with True/False value or kActive/kNotActive. It would be fantastic if H5Web can support to plot this kind of two-value signal as 0/1.

**Comment by axelboc** [comment]
Hi @Yayanzjg, I've transferred the issue to the `h5web` repository. Will reply there :blush:

**Comment by axelboc** [comment]
Hi @Yayanzjg, could you please share an example HDF5 file and maybe a screenshot of the visualization you're after made with another tool like matplotlib?

**Comment by xbaelus** [comment]
Hi! @axelboc I'd love to have this in **vscode-h5web**, but since the issue here is still open, not sure if I should open another issue there?

**Comment by axelboc** [comment]
@xbaelus you're in the right place! Thanks for letting us know.

**Comment by axelboc** [comment]
@xbaelus please keep an eye out for the next releases of H5Web and vscode-h5web. Might take us a few weeks. 😉

**Comment by xbaelus** [comment]
Thanks a lot for taking care of this @axelboc ! :smile:
