### ISSUE TITLE
[Dimension mapper] Slider for extra dimension

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#150]
This is part of epics #73 and #65 and follows #149.

![axis-dim-mapping](https://user-images.githubusercontent.com/2936402/82642413-2b690700-9c0e-11ea-8f28-0be6135d457c.png)

- 2D dataset: show a slider for the second dimension not assigned to `x`.
- 3D dataset: show a slider for the third dimension not assigned to `x` or `y`.
- Add small 3D dataset to mocked data and test feature with `MockProvider`.
- Manage slider state in `DatasetVisualizer` and use in `VisProvider` to slice the 1D or 2D values array that is passed through the context.

**Comment by loichuder** [comment]
First step in #156

**Comment by loichuder** [comment]
Functional in #160

**Comment by loichuder** [comment]
Done in #169
