### ISSUE TITLE
Please update documentation for H5Provider  - axiosConfig vs axiosParams

### ISSUE THREAD

**Issue by vedina** [silx-kit/h5web#1526]
### Describe the bug

According to [June 15, 2022 commit ](https://github.com/silx-kit/h5web/commit/35943d8ef0e347c96ffbdf44d173992331fe3281 ) H5GroveProvider no more accepts axiosParams , but the documentation is not updated

### To Reproduce

Go to https://github.com/silx-kit/h5web/blob/main/packages/app/README.md 

````
<H5GroveProvider
  url="https://h5grove.server.url"
  filepath="some-file.h5"
  axiosParams={{ file: 'some-file.h5' }}
>
  <App />
</H5GroveProvider>
```

The demo app is indeed up-to-date

```
<H5GroveProvider
      url={URL}
      filepath={filepath}
      axiosConfig={{ params: { file: filepath } }}
    >
      <App sidebarOpen={!query.has('wide')} getFeedbackURL={getFeedbackURL} />
    </H5GroveProvider>
```

**Comment by axelboc** [comment]
Thanks for the report!
