### ISSUE TITLE
[Line] Tooltip not visible for x<1 on `to_merge` dataset

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#153]

**Comment by axelboc** [comment]
By the way, once #152 is merged, we can remove the calls to `Math.floor` in `formatIndex` and `formatValue` and to the flooring of the coordinates directly in `TooltipMesh`.

**Comment by loichuder** [comment]
> That is not a bug, that's a feature.

I preferred to hide the tooltip completely when there was no valid `y` at the pointed `x` by setting `value` to `undefined` (https://github.com/silx-kit/h5web/blob/master/src/h5web/visualizations/shared/TooltipMesh.tsx#L76).

What behaviour do you propose instead ?

**Comment by axelboc** [comment]
The tooltip should still be visible between 0 and 1, shouldn't it?

**Comment by axelboc** [comment]
Ah I see it now, it's `&& value` that should be `&& value !== undefined`.

**Comment by loichuder** [comment]
Yeah, my bad. I misread the issue name.
