### ISSUE TITLE
Do not know how to serialize a BigInt

### ISSUE THREAD

**Issue by just-hello** [silx-kit/h5web#1536]
### Describe the bug

When I use the H5Web extension on vscode and open the .h5 file, this display appears：
![image](https://github.com/silx-kit/h5web/assets/65025212/1b035011-0307-4ff1-8d06-84b47c7379cb)
Here is the file I want to open:
[zsim.zip](https://github.com/silx-kit/h5web/files/13770153/zsim.zip)

**Comment by axelboc** [comment]
Hi @just-hello, thanks for the report!

The dataset you're trying to visualise has a very complicated compound dtype made of nested compound and array fields:
![image](https://github.com/silx-kit/h5web/assets/2936402/65cd2982-038c-42c5-8043-26a6f6e913c5)

None of H5Web's visualizations currently support such a complex structure. The _Raw_ visualization therefore acts as a fallback that reads the dataset and tries to display it as a JSON string. The error you're seeing comes from the _Raw_ visualization's attempt at converting the JS object provided by [h5wasm](https://github.com/usnistgov/h5wasm) (which includes BigInt numbers) into a JSON string.

This same error was previously reported in https://github.com/silx-kit/vscode-h5web/issues/30, but in that case, the dataset was simple enough that it was supposed to be supported by the _Matrix_ visualization. It seems that the fix in #1503 was therefore not generic enough. I think I have found a better solution—I will investigate.

Note, however, that even if the _Raw_ visualization manages to convert the dataset to a JSON string, it will likely be too big to display and your only option will be to download it as a JSON file via the toolbar (cf. screenshot below). Will this behaviour be satisfactory to you?

![image](https://github.com/silx-kit/h5web/assets/2936402/f5c04bd1-4b62-45c4-88e1-e445d09e73af)

**Comment by just-hello** [comment]
Thank you for the explanation. A download option for JSON data would be fine.
