### ISSUE TITLE
Open a new hdf5 file directly instead of saving

### ISSUE THREAD

**Issue by dockeratso** [silx-kit/h5web#1558]
### Is your feature request related to a problem?

Open the page https://h5web.panosc.eu/h5wasm 
in the a browser tab. Drop a hdf5 file to open it. Then drop another file into the same browser tab.   At the moment the file is being download instead of shown.

### Requested solution or feature

The requested feature is to open the second file (when dropped) and show the content of that file instead of the first file, Otherwise I need to reload the clean viewer and drop the file on that one.

**Comment by axelboc** [comment]
Hi @dockeratso! The h5wasm demo is purposely limited in terms of features, as it is only meant to demonstrate and test H5Web's [`H5WasmProvider`](https://github.com/silx-kit/h5web/blob/main/packages/h5wasm/README.md). We recommend you use **[myHDF5](https://myhdf5.hdfgroup.org/)** instead, which includes the feature you request. :wink:
