### ISSUE TITLE
[Heatmap] Add option to flip x-axis in the toolbar

### ISSUE THREAD

**Issue by itcarroll** [silx-kit/h5web#1573]
### Requested solution or feature

I would like to be able to flip the x axis in the heatmap vizualization, just like I can currently flip the y axis.

Remote sensing data sometimes is produced that way. Swapping the axes and then rotating the axis formerly known as x gives me a rotated view, which is better but not ideal.

Thank you for an awesome tool.

**Comment by axelboc** [comment]
Hey @itcarroll, thanks for the feedback. I've implemented this in #1574, so it will go out in the next release. :wink:
