### ISSUE TITLE
NeXus visualization with H5Web/h5wasm unstable?

### ISSUE THREAD

**Issue by bmaranville** [silx-kit/h5web#1611]
Hello - 

I was hoping to use h5web with h5wasm as an official tool for visualizing NeXus datasets from our facility, but I see there is a new warning on the h5web website that this combination might not be expected to be stable?

![image](https://github.com/silx-kit/h5web/assets/686570/6650a6cc-97bc-4b4d-89d6-fa0059f24d2b)

We in particular need a solution that includes the NeXus-specific features present in H5Web, so that myHDF5 is not a good alternative solution (as far as I understand, myHDF5 does not include NeXus lookups)

What do you recommend to use for a production tool for NeXus visualization?

**Comment by axelboc** [comment]
Hi @bmaranville, **[myHDF5](https://myhdf5.hdfgroup.org/)** does include all the features of the demo at https://h5web.panosc.eu/h5wasm, including the NeXus lookups. Internally, it basically uses the same [`App`](https://github.com/silx-kit/h5web/blob/main/packages/app/README.md#app) component from `@h5web/app`. 

In fact, it has _more_ features than the demo: it allows opening multiple files and easily switching between them, exporting datasets to CSV, converting GitHub file URLs, etc. It's even linked from the HDF Group's [homepage](https://hdfgroup.org/), so you can definitely consider it the official h5wasm-based tool for visualizing NeXus datasets. 😉
