### ISSUE TITLE
z-range is only -3..3

### ISSUE THREAD

**Issue by vallsv** [silx-kit/h5web#1626]
### Is your feature request related to a problem?

I use a lot the z-index.

But i saw that the range is clamped to something quite small like 0..3 or -3...3

Outside, a component is hidden.

I have to use a lot of layers for my use cases.

Sure i still can divide 0..3 by an infinite amount of values. But i feel like more easy to deal with integer.

### Requested solution or feature

Use a bigger range for the z-buffer, maybe something like 0..1000 or -1000..1000, i don't know.

### Alternatives you've considered

Rescale the z-depth on my side.

### Additional context

I use @h5web/lib": "7.0.2-beta.0

**Comment by axelboc** [comment]
Stacking has been sorted out in [v7.1.0](https://github.com/silx-kit/h5web/releases/tag/v7.1.0) with some additional bug fixes in later versions. I recommend you upgrade first then check out the [_Stacking_](https://h5web-docs.panosc.eu/?path=/docs/stacking--docs) documentation page. If you're still stuck at that point, let me know and we'll try to figure it out.

**Comment by vallsv** [comment]
Hi, thanks for the answer.

But i only talk about the opengl canvas z-buffer.

I fact i don't use any SVG components.

**Comment by axelboc** [comment]
Can you make a basic repro? Because, you're not giving us much to go on here. 😅 You can use [this sandbox](https://codesandbox.io/p/sandbox/h5weblib-vite-xru04) as a base and replace one of the visualizations with a `Canvas` with some R3F/ThreeJS children.

**Comment by vallsv** [comment]
Here is an example.

As you can see the violet and the red are not visible because outside of the z-index.

So the visible z-range is in fact [-995...4].

```
import React from "react";
import { VisCanvas } from "@h5web/lib";

export default function App() {
  const width = 1000;
  const height = 1000;

  const stuffs = [
    {color:"#FF0018", z:-996, size:6},
    {color:"#FFA52C", z:-995, size:5},
    {color:"#FFFF41", z:-1, size:4},
    {color:"#008018", z:1, size:3},
    {color:"#0000F9", z:4, size:2},
    {color:"#86007D", z:5, size:1},
  ]

  return (
      <VisCanvas
        abscissaConfig={{
          visDomain: [-width, width],
          label: "x (px)",
        }}
        ordinateConfig={{
          visDomain: [-height * 0.6, height * 0.6],
          label: "y (px)",
        }}
        aspect="equal"
        showAxes
      >
        {stuffs.map((stuff, index)=> (
          <mesh key={`m${index}`} position-z={stuff.z}>
            <ambientLight />
            <planeGeometry attach="geometry" args={[stuff.size*50, stuff.size*50, 1, 1]} />
            <meshBasicMaterial
              attach="material"
              transparent={true}
              color={stuff.color}
              opacity={1}
            />
          </mesh>
        ))}
      </VisCanvas>
  );
```
![image](https://github.com/silx-kit/h5web/assets/7579321/05f90d2d-98da-4018-b51b-65b80394b9be)

**Comment by axelboc** [comment]
Thanks! Okay, so this seems to somewhat match the [`far` setting](https://docs.pmnd.rs/react-three-fiber/api/canvas) of R3F's default [orthographic camera](https://github.com/pmndrs/react-three-fiber/blob/62cecea9bf3fbe97f9a04dd830f4dc28b2b47c37/packages/fiber/src/core/index.tsx#L225). The camera itself seems to be positioned at a `z` coordinate of 5, which explains why the range is `[-995 5[`.

We could maybe move the camera to a `z` coordinate of `1000` to make things easier?

**Comment by vallsv** [comment]
You could use 500, so the range would be synetric -500, 500.

But if there possibility to setup the camera, i think it's even better to setup something like `{near: -1000, far: 1000, position: [0, 0, 0]}`. Maybe @t20100 would have a better feedback than me here.

**Comment by axelboc** [comment]
... or `[-1000 1000[` with the default `near: 0.1`.

**Comment by loichuder** [comment]
> Two ways to fix this:

Heh. There is a third one: use line segments instead of a single line and do no render the segments with an invalid point to avoid dealing with them in the display :smile_cat:  

> For this reason, I propose the following camera configuration: { near: 0, far: 1000, position: [0, 0, 1000] }

Sounds ok to me 👍

**Comment by axelboc** [comment]
> Heh. There is a third one: use line segments instead of a single line and do no render the segments with an invalid point to avoid dealing with them in the display 😸

Haha yes, indeed. Downside of course is larger geometry buffers and more complicated code with look-ahead or look-behind logic.

**Comment by vallsv** [comment]
> is incompatible with the technique we use to hide points with NaN or infinite coordinates.

If you use the z buffer to hide stuffs, i think it's a very bad idea.

**Comment by axelboc** [comment]
Thanks for your input.

**Comment by t20100** [comment]
threejs logs some errors for NaN & Inf, so this is not a neat way, IMO using the z-buffer nicely workaround this and sparses using segments and indices.

+1 for `[0, 1000]` z-range (and anyway it's configurable)
