### ISSUE TITLE
Show field names in Scalar view for Compound Datatypes

### ISSUE THREAD

**Issue by Blackclaws** [silx-kit/h5web#1649]
### Is your feature request related to a problem?

Right now when viewing an array of compound datatypes there are column headers that contain the field names. When viewing a scalar compound value that isn't the case and it becomes quite useless that way.

### Requested solution or feature

Implement same view for scalar values as for arrays.

**Comment by axelboc** [comment]
Scalar compounds are now supported in [myHDF5](https://myhdf5.hdfgroup.org/).
