### ISSUE TITLE
Committed datatypes

### ISSUE THREAD

**Issue by JonasIsensee** [silx-kit/h5web#1699]
I encountered some reproducable errors and reduced it to the following:
Committed compound datatypes that are linked *like* a dataset to a group cause the viewer / backend to crash:

In this reproducer, I've placed the committed type into a subgroup. Therefore the file can normally be loaded into myHDF5 web viewer and the error only occurs when trying to view the contents of `/types/`.

Here's the h5dump of the example file used below:
```
HDF5 "test.h5" {
GROUP "/" {
   DATASET "data" {
      DATATYPE  "/types/AStruct"
      DATASPACE  SIMPLE { ( 1, 1 ) / ( 1, 1 ) }
      DATA {
      (0,0): {
            1,
            2
         }
      }
   }
   GROUP "types" {
      DATATYPE "AStruct" H5T_COMPOUND {
         H5T_STD_I64LE "x";
         H5T_IEEE_F64LE "y";
      }
   }
}
}
```

<details>

```
HDF5-DIAG: Error detected in HDF5 (1.14.2) thread 0:
  #000: /__w/libhdf5-wasm/libhdf5-wasm/build/1.14.2/_deps/hdf5-src/src/H5D.c line 403 in H5Dopen2(): unable to synchronously open dataset
    major: Dataset
    minor: Can't open object
  #001: /__w/libhdf5-wasm/libhdf5-wasm/build/1.14.2/_deps/hdf5-src/src/H5D.c line 364 in H5D__open_api_common(): unable to open dataset
    major: Dataset
    minor: Can't open object
  #002: /__w/libhdf5-wasm/libhdf5-wasm/build/1.14.2/_deps/hdf5-src/src/H5VLcallback.c line 1980 in H5VL_dataset_open(): dataset open failed
    major: Virtual Object Layer
    minor: Can't open object
  #003: /__w/libhdf5-wasm/libhdf5-wasm/build/1.14.2/_deps/hdf5-src/src/H5VLcallback.c line 1947 in H5VL__dataset_open(): dataset open failed
    major: Virtual Object Layer
    minor: Can't open object
  #004: /__w/libhdf5-wasm/libhdf5-wasm/build/1.14.2/_deps/hdf5-src/src/H5VLnative_dataset.c line 321 in H5VL__native_dataset_open(): unable to open dataset
    major: Dataset
    minor: Can't open object
  #005: /__w/libhdf5-wasm/libhdf5-wasm/build/1.14.2/_deps/hdf5-src/src/H5Dint.c line 1425 in H5D__open_name(): not a dataset
    major: Dataset
    minor: Inappropriate type


Here is some additional context:

  - User agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0
  - Location: https://myhdf5.hdfgroup.org/view?url=blob%3Ahttps%3A%2F%2Fmyhdf5.hdfgroup.org%2F66f3acf9-1943-41aa-8269-a4d90b9092c3
  - File name: test.h5
  - File URL: blob:https://myhdf5.hdfgroup.org/66f3acf9-1943-41aa-8269-a4d90b9092c3
  - Service detected: Local
  - Resolved URL: blob:https://myhdf5.hdfgroup.org/66f3acf9-1943-41aa-8269-a4d90b9092c3

```
</details>

**Comment by axelboc** [comment]
Thanks for the report. Indeed, committed datatypes are not currently supported by [h5wasm](https://github.com/usnistgov/h5wasm). You can reproduce also by selecting the `datatypes` group in the `epic.h5` file in the [h5wasm demo](https://h5web.panosc.eu/h5wasm?url=https%3A%2F%2Fwww.silx.org%2Fpub%2Fh5web%2Fepics.h5) (vs in the [h5grove demo](https://h5web.panosc.eu/h5grove?file=epics.h5)).

I will use this issue to track progress:

- [ ] Support inspecting committed datatypes with h5wasm providers.
- [ ] Support visualizing datasets with committed datatypes with h5wasm providers.

**Comment by bmaranville** [comment]
@JonasIsensee can you post the `test.h5` file you're using here?

**Comment by JonasIsensee** [comment]
Ah, I didn't know the link in the error message `blob:https://myhdf5.hdfgroup.org/....` expired so quickly.
Here's an equivalent file (as tar so that github allows me to upload it..)
[committed_type.h5.tar.gz](https://github.com/user-attachments/files/16739386/committed_type.h5.tar.gz)
