### ISSUE TITLE
Optimise uses of ndarray

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#170]
- [x] Split `useMemo` in two in `VisProvider` (one for ndarray creation, one for slicing).
- [x] Simplify `unpack(mappedView).flat()` by unpacking a flat array directly.
- [ ] ~Find domain with cwise.~
- [ ] ~Create data points for line vis with cwise.~
- [ ] ~Create typed array for heatmap texture without calling `flat` (pick => shape 1D => unpack), or even without calling `Float64Array.from` (cwise + push to buffer).~ - no longer calling `flat`

**Comment by loichuder** [comment]
WIP at #178. 
Waiting for `cwise` to support recent ES versions to go further (https://github.com/scijs/cwise/pull/25).

**Comment by axelboc** [comment]
I think #198 brings us to a good state. The `cwise` optimisations no longer seem relevant anyway. There are still a few places where the code could be optimised (e.g. `findDomain` called twice with log scale and negative/positive domain, two uses of `findDomain(values.filter())` which amounts to two loops, etc.), but I don't think the gain would be worthwhile when compared to the increase in code complexity.

**Comment by loichuder** [comment]
> There are still a few places where the code could be optimised (e.g. `findDomain` called twice with log scale and negative/positive domain, two uses of `findDomain(values.filter())` which amounts to two loops, etc.), but I don't think the gain would be worthwhile when compared to the increase in code complexity.

Yes, I think the performance is not an issue right now: things are running quite smoothly. Let's wait until we get more complains on that :smile:
