### ISSUE TITLE
[Line] Too many ticks with log scale

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#183]
![image](https://user-images.githubusercontent.com/2936402/84774125-adfe9f80-afdd-11ea-994f-668add4ee872.png)

**Comment by axelboc** [comment]
The new version of `d3-scale` may fix this issue.

**Comment by axelboc** [comment]
Turns out log scales don't have a customisable number of ticks. We do want to show all the ticks and grid lines in order to clearly convey that the axis is logged. What we don't want is to show all the labels. https://groups.google.com/g/d3-js/c/lF8WcDnVtQ8/m/Ef8f0ofW9TUJ

**Comment by loichuder** [comment]
About **Attempt n°2**, even using 
```
tickFormat={yTicksScale.tickFormat(adaptedNumTicks(height))}
```
(without specifier) leads to missing ticks :disappointed:
