### ISSUE TITLE
[Heatmap] Add log scale

### ISSUE THREAD

**Issue by loichuder** [silx-kit/h5web#184]
Symlog scale for Heatmap was added in #79 but there is no "true" log scale yet.

As in #74, we have to decide on the behaviour of unsupported values (i.e negative values). I see two options for now:
- deactivate completely the log option in the presence of such values
- allow the log to be selected and set the pixels of unsupported values to a neutral colour

Note that, contrary to the LineVis, the domain of the scale can be selected by the user. Therefore, the behaviour must be able to change dynamically.

**Comment by loichuder** [comment]
I put some thoughts in this:
> - deactivate completely the log option in the presence of such values

Then, we would need a fallback behaviour when switching datasets/changing to a domain of unsupported values. Should it fallback to Symlog or Linear ? 

This might prove inconvenient for users as the scale type may end up switching from Log to other values when exploring datasets.

> - allow the log to be selected and set the pixels of unsupported values to a neutral colour

Tough to say what would be the neutral color as we support multiple colormaps of different hues. A bright red `(255, 0, 0)` fits most cases but is too eye-catching in my opinion.

Also, it will be tough to integrate in our `HeatmapVis` as it is. To allow this behaviour, we would indeed need to compute a domain of supported values (let's call it `supportedDomain`) as done in https://github.com/silx-kit/h5web/blob/master/src/h5web/visualizations/line/LineVis.tsx#L27 and I see several problems:
- Computing the domain must be done at two places (`ColorBar` and the hook computing `TextureData`) but `ColorBar` has no access to the `values` array. It would need then to be passed as props or through the store but neither feels right. The ideal would be to compute `supportedDomain` in the HOC `HeatmapVis`. We then run in the next problem
- The `dataDomain` and the `customDomain` are handled through the store. To integrate seamlessly the `supportedDomain`, it would need to be in the store as well. But we end up with three different domains in the store which hints me that we are doing something wrong
- Also, the interplay with `customDomain` is not clear. Should `customDomain` overwrite `supportedDomain` ? Then, what would happen of the DomainSlider: should it display the "true" `supportedDomain` or leave the user choose its own domain ? Or something in-between where we clamp the limits of the domain to the supported values ? On a related note, would it be possible to add some complexity to the `setCustomDomain` method to handle this interplay ?

@axelboc Your thoughts ?

**Comment by axelboc** [comment]
How about showing "Log scale not supported for this dataset"? 😄

**Comment by axelboc** [comment]
It's not great if people are slicing through nD datasets and one of the slices happens to have negative values, but I'm hoping that people who are interested in the real log scale would not be confronted to this scenario... We need to ask users.

**Comment by loichuder** [comment]
> It's not great if people are slicing through nD datasets and one of the slices happens to have negative values, but I'm hoping that people who are interested in the real log scale would not be confronted to this scenario... We need to ask users.

At least it will be better than forcing a scale change...
