### ISSUE TITLE
[dev] Upgrade to TypeScript 4.0

### ISSUE THREAD

**Issue by loichuder** [silx-kit/h5web#185]
https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/

There are no "major breaking changes" and the improvements could strengthen the typing in several situations we encountered (e.g. for array operations: https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/#variadic-tuple-types).

**Comment by axelboc** [comment]
I don't think they've applied the variadic tuple syntax to the array methods yet. I wasn't able to remove many type assertions.

**Comment by axelboc** [comment]
Argh... Our version of ESLint doesn't support TS v4. We need to wait for CRA v4. Closing for now -- we can re-open it in due time.

**Comment by loichuder** [comment]
Done in #270
