### ISSUE TITLE
[storybook] Minor complains on AxisSystem

### ISSUE THREAD

**Issue by loichuder** [silx-kit/h5web#187]
- Why the AxisSystem does not take all available space ? Is it on purpose ?
![image](https://user-images.githubusercontent.com/42204205/92708479-72624000-f356-11ea-898f-a2104b7d9dd8.png)

- For `showGrid`, I would put `showGrid: false` in the config instead of removing it completely.

**Comment by axelboc** [comment]
- My guess is there's a min-height somewhere -- the canvas takes the available height, and then the aspect ratio forces it to shrink in width.
- Yep, sounds good.
