### ISSUE TITLE
Rendering performance of HeatmapVis when config changes

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#193]
See https://github.com/silx-kit/h5web/pull/192#discussion_r487878841 - use `memo` where needed.

**Comment by loichuder** [comment]
To be noted that I have again a flickering of the texture at the end of the computation when changing dimensions... I think we had this a few months (!) ago

**Comment by axelboc** [comment]
Hmm, yeah, it was to do with the `useMemo` dependencies in `useTextureData`.

As discussed via chat, we should also add [some profiling](https://reactjs.org/docs/profiler.html) to the visualizations.

**Comment by axelboc** [comment]
Resolved in #192 and with #195 and #197.
