### ISSUE TITLE
Consider using more utilities from drei

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#201]
`drei`, R3F's companion utility library, has had some major changes since we started using it. We should:

- [ ] use [`Shapes`](https://github.com/pmndrs/drei#shapes), which should simplify the use of Three's buffer geometries (notably when it comes to updating geometries dynamically);
- [ ] look for other potential simplifications (e.g. `Line`, `Loader`, etc.)

**Comment by axelboc** [comment]
I've opened a PR https://github.com/pmndrs/drei/pull/148 to fix tree-shaking, but now that we've implemented our own `Html` element, I no longer think `drei` is worth using. The simplifications it would bring are listed below.

### `Plane` (3 occurrences)

```tsx
// before
<mesh material={material}>
  <planeBufferGeometry attach="geometry" args={[width, height]} />
</mesh>

//after
<Plane material={material} args={[width, height]} />
```

### ~~`Line` abstraction~~

The [`Line` abstraction](https://github.com/pmndrs/drei#line-) is a bit trickier because we're sharing the points geometry between the `line` and `points` objects.

### `useTextureLoader`

```tsx
// before
const sprite = useLoader(TextureLoader, glyphURL || GLYPH_URLS.Cross);

// after
const sprite = useTextureLoader(glyphURL || GLYPH_URLS.Cross);
```

**Comment by loichuder** [comment]
I also don't think the simplifications are worth it.

Moreover, I think the syntax `mesh` + `planeBufferGeometry` can be simplified with the new R3F release (5.0.0).
