### ISSUE TITLE
[Nexus] Line vis for 1D @signal (no @axes)

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#231]
Part of epic #196 

### First-issue prerequisites

- [x] Mock Nexus data
- [ ] Nexus support detection + Nexus visualization
  - Pass groups to `DatasetVisualizer`
  - Add vis component and vis def
  - Show vis when group has `NX_class="NXdata"` attribute

**Comment by loichuder** [comment]
First part done in #240
