### ISSUE TITLE
Route to demo HSDS provider

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#26]
- I'm thinking `/hsds` for now?
- [React Router](https://reacttraining.com/react-router/web/guides/quick-start) to manage routing

**Comment by loichuder** [comment]
Agreed.

It may also be the occasion to fix the hard-typed config in HSDS.

**Comment by loichuder** [comment]
Done in 301f4bff828a7b1367f48563e4db3f408e020ea5
