### ISSUE TITLE
[NeXus] Add support for `NXdata@SILX_style` Nexus extension for defining signal scale

### ISSUE THREAD

**Issue by t20100** [silx-kit/h5web#281]
The extra `NXData@SILX_style` attribute allows to define the default normalization to use for the Nexus signal and axes.
`@SILX_style` contains a json string with a mapping defining extra parameters:
- `"signal_scale_type"`: string (either `"log"` or `"linear"`)
- `"axes_scale_type"`: list of strings (also either `"log"` or `"linear"`)

The idea is to first support the `"signal_scale_type"` parameter which allows to define the default normalization of the colormap for image and the Y axis scale for curve with:

`@SILX_style = {"signal_scale_type": "log"}`

More exemples: https://github.com/silx-kit/silx/issues/2928#issuecomment-639572971

Related issue https://github.com/silx-kit/silx/issues/2928 and PR https://github.com/silx-kit/silx/pull/3092 with discussions.

**Comment by loichuder** [comment]
- [ ] Support `axes_scale_type` for `LineVis`
- [ ] Support `signal_scale_type` for `LineVis`
- [ ] Support `signal_scale_type` for `HeatmapVis`

`axes_scale_type` for `HeatmapVis` seems out of scope. Also, it would imply reviewing completely how the texture is computed.

**Comment by t20100** [comment]
Yes, there is no need for `axes_scale_type` for images.

**Comment by axelboc** [comment]
Note that for `signal_scale_type`, the toolbar will need to be updated with the specified scale type.

Also, I suggest we limit the scope of this issue to supporting only linear/log/symlog for `signal_scale_type` on `HeatmapVis`.

**Comment by loichuder** [comment]
[All milestones closed](https://github.com/silx-kit/h5web/issues/281#issuecomment-724811613). Closing this.
