### ISSUE TITLE
[NeXus] NXdata `title` dataset support

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#282]
Part of #196. It should be used first when present to determine the plot title. The resulting order of priority is as follows:

1. `title` dataset (scalar string) in NXdata group
2. `long_name` attribute on signal dataset
3. signal name + `unit` attribute on signal dataset
4. signal name

Note that this only applies to the plot title, not to the axis labels, so we may have to introduce a new utility function on top of `getDatasetLabel`, like `getVisTitle`.

**Comment by loichuder** [comment]
Some tests can be added:
- display title on Line vis from dataset name and unit attribute
- display title on Heatmap vis from dataset name
- display title on NeXus vis from "title" dataset
- display title on NeXus vis from long_name attribute on signal dataset

**Comment by loichuder** [comment]
Implementation in #291 

Tests are a separate issue #292
