### ISSUE TITLE
[Nexus] Add support for complex data

### ISSUE THREAD

**Issue by loichuder** [silx-kit/h5web#310]
By complex data, I mean numbers that have a real and an imaginary part :wink:

**Comment by t20100** [comment]
A sample dataset: http://ftp.esrf.fr/pub/scisoft/PyNX/data/ptycho-siemens-star-id01-result.cxi

**Comment by loichuder** [comment]
A first implementation of complex vis was done in https://github.com/silx-kit/h5web/pull/634: it uses the HeatmapVis to show the phase as color and the amplitude as transparency.

Based on recent feedback, we should in fact implement a three-fold vis where we can switch between:
- Phase as colour, amplitude as transparency (current behaviour)
- Only phase as colour
- Only amplitude as colour

**Comment by axelboc** [comment]
I think a single "Complex" vis with a drop-down selector in the toolbar would make more sense than separate visualizations.

**Comment by axelboc** [comment]
👏
