### ISSUE TITLE
[NeXus] nD `errors` dataset support

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#316]
I tried using a 2D dataset for the `nexus_entity/spectrum` NXdata group, to check that the `spectrum` interpretation is chosen over the dataset's dimensions. I got this error:

![image](https://user-images.githubusercontent.com/2936402/99561247-0be94600-29c7-11eb-8e1b-6e08d8801013.png)

When I use a 2D dataset for the errors, I get another similar error.

**Comment by loichuder** [comment]
From [NXdata doc](https://manual.nexusformat.org/classes/base_classes/NXdata.html):
> If available, the standard deviations of the data are to be stored in a data set of the same rank and dimensions, with the name errors.

Still, it should be working if you use a 2D dataset for the errors. What is the exact error you have in this case ?

**Comment by vasole** [comment]
With the name DATASET_errors

**Comment by vasole** [comment]
The general rule is to use for DATASETNAME DATASETNAME_errors. 

The errors in the NXdata group is still there but you should consider the generic case.

**Comment by loichuder** [comment]
Fixed by #330
