### ISSUE TITLE
Line plots of 2d matrix

### ISSUE THREAD

**Issue by andygotz** [silx-kit/h5web#36]
It would be useful to have the option to display a line plot of a 2d image by selecting a row or column to plot and in the future an arbitrary cut.

I am not sure if this is part of the 2d display widget or if the line display should be able to handle 2d images? 

I leave it to the developers to make a proposal.

**Comment by vasole** [comment]
The extraction of profiles is foreseen in the library.

**Comment by loichuder** [comment]
Line plots for row/columns of 2D datasets (and beyond) were implemented in #169

**Comment by axelboc** [comment]
Closing as out of scope. We agreed last month that this type of feature would not be implemented within the viewer, but as a separate application(s) focused on data analysis.
