### ISSUE TITLE
Support external/soft links

### ISSUE THREAD

**Issue by loichuder** [silx-kit/h5web#364]
We need to test and see how/if we can resolve the following entities:
- [ ] External links
- [ ] Soft links
- [ ] Virtual datasets ?

**Comment by axelboc** [comment]
The front-end soft link resolution should be easy to do now. It can be done right after the tree is created, once all hard links have been resolved, by recursively searching the tree for soft links and taking advantage of the new `getEntityPath` utility.

**Comment by loichuder** [comment]
Soft links and virtual datasets are resolved directly by JupyterLab backend :partying_face:

**Comment by loichuder** [comment]
After discussion, we will rely on the back-end to provide the link resolution. 

Resolution on the front-end will there not be implemented.
