### ISSUE TITLE
Problem with switching scale on fully negative curves

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#373]
- http://localhost:3000/mock
- `nD_datasets/threeD`
- Switch to log on `Y` => curve disappears
- Go to other dataset and come back
- Switch to linear on `Y` => curve doesn't reappear! 🤷‍♂️

**Comment by loichuder** [comment]
Can you try with the code before https://github.com/silx-kit/h5web/pull/371 was merged ?

**Comment by axelboc** [comment]
It was working before, so it's a regression 😢
