### ISSUE TITLE
User-friendly README

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#401]
- [x] Move dev stuff to `CONTRIUBUTING.md`
- [x] Embellish and improve `README.md` (e.g. include a screenshot)

**Comment by loichuder** [comment]
>     * Embellish and improve `README.md` (e.g. include a screenshot)

Or an animated GIF :sparkles:

**Comment by axelboc** [comment]
Putting the GIF here to generate a URL:

![h5web](https://user-images.githubusercontent.com/2936402/102904182-ab3fa400-4471-11eb-9c7a-606deffebc43.gif)
