### ISSUE TITLE
Data fetching strategy 2.0

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#417]
### Background

Our data fetching strategy is built on the concept of **Data Providers** that act as interfaces between back-end APIs (typically REST) and the H5Web application. A data provider injects functions through React Context that allow any component to request the data it needs, when it needs it:

```jsx
// app entrypoint
<SilxProvider domain="bsa_002_000-integrate-sub">
  <App />
</SilxProvider>

// internal component of H5Web
const { getValue } = useContext(ProviderContext);
useEffect(() => {
  getValue(myDataset.id).then(...);
}, [])
```

Data providers must all respect the same context provider contract by rendering the same high-level `Provider` component provided by H5Web. In our initial implementation, this contract was as follows:

```jsx
return <Provider api={{ domain, getMetdata, getValue }}>{children}</Provider>
```

`getMetadata` and `getValue` are asynchronous functions. The former is expected to return the entire metadata tree, and the latter is expected to return the value of a dataset given its ID.

### Limitations

The main limitations of our initial implementation are as follows:

- **The entire metadata tree must be fetched at once** (entities, attributes, children). This is problematic for the following reasons:
  - Real-world HDF5 back-ends (e.g. HSDS, Jupyter Lab HDF5 extension), don't provide endpoints to fetch an HDF5 file's entire metadata tree. They only provide endpoints to fetch the metadata of a specific entity ... and even specific parts of the entity's metadata (i.e. only the children or the attributes). Fetching the whole metadata tree at once therefore requires performing a very large number of requests in a waterfall manner. This takes a long time even for simple HDF5 files and is impractical for large files.
  - For very large HDF5 files (or files with lots of external links pointing to other files with lots of external links), transferring the whole metadata tree over the network is time-consuming, or at least very wasteful, especially considering that a user may wish to inspect only a specific branch of the tree in H5Web.
- **Data providers must manage their own cache**. This is problematic for the following reasons:
  - A data provider could implement its cache poorly or not implement one at all, leading to poor performance in H5Web.
  - The caching requirements are similar for all providers, leading to duplicated logic and unnecessarily tedious implementation. **_EDIT_** Note that some providers may require more internal caching if the data expected by H5Web is more atomic than the available endpoints (e.g. if an endpoint returns both the metadata and the attributes of an entity while H5Web requests both separately).
- **The providers' caches are not exposed through context**. The only functions available to H5Web's internal components are asynchronous functions, which means that even if the data is already available in cache, the use of this data in a component necessarily happens asynchronously (i.e. with at least two renders). When `Suspense` is involved, this leads to a _Flash of Loading Component_.

### RFC

- Data providers should not have to implement caching or hold state. They should be thin adapters of their respective back-end APIs -- i.e. as close as possible to one endpoint = one function, including for entity metadata endpoints.
- The high-level `Provider` should handle caching and expose methods to access this cache through context.
- H5Web components should have access to hooks to:
  - abstract away the decision of either fetching new data (and rendering asynchronously with `Suspense`) or reading existing data from cache (and rendering synchronously without `Suspense`);
  - prefetch data intelligently, especially metadata, so users see as few loading states as possible.

### Roadmap

We should start by moving the existing cache implementations for dataset values out of the data providers and into the high-level `Provider`, exposing a function to read this cache through context, and updating our `useDatasetValue` and `useDatasetValues` hooks to allow for synchronous rendering when reading from cache.

**Comment by t20100** [comment]
It also sounds like the backends should provide more appropriate endpoints for fetching metadata.

**Comment by axelboc** [comment]
So far, we now have a suspense library, [react-suspense-fetch](https://github.com/dai-shi/react-suspense-fetch), that is lower-level and therefore less tedious to use than our previous library, [use-async-resource](https://github.com/andreiduca/use-async-resource). 

`react-suspense-fetch` allows us to create individual caches based on async functions. So far we have:

- `valuesStore`, based on API method `async getValue(id: HDF5Id): HDF5Value`;
- `groupsStore`, based on API method `async getGroup(path: string): Group`.

My initial idea was that `getGroup` would return a complete `Group` object, containing the group's attributes, its children, its children's attributes and metadata (shape, type, etc.) ... but not the group's nested children (i.e. the children of its children).

- The upside of this approach is that `groupsStore` would be the only store/cache needed to store all of the metadata of an HDF5 file, which would limit the number of "suspended" components and fallback loaders in H5Web and would hugely simplify the parsing of NeXUS entities. The initial loading of the group would take time, but the children datasets' metadata would afterwards be instantly available.
- The downside is that requesting a group could still lead to a large number of requests with potentially heavy, unused payloads, as both HSDS and Jupyter provide separate endpoints for fetching a group's links/children and their individual metadata. This could lead to a group being very slow to expand in the Explorer, or to a group's metadata being very slow to appear in the Inspector, if, for instance, the group were to have thousands of children or an attribute with a very large value.

So there are a few possible directions we can take from here on:

#### 1. Maintain the current approach

We could mitigate the downside of making too many requests by implementing a custom endpoint for `getGroup` in each back-end to fetch a group's entire metadata, up to and including its direct children's metadata. Of course, the problem is that the core maintainers of the back-ends may not accept a request to implement such an endpoint. Also, we would still be left with potentially very heavy payloads because of attributes.

#### 2. Follow the lead of the back-ends and create more atomic stores

Both HSDS and Jupyter currently provide separate endpoints for fetching: an entity's metadata (`type`, `shape`, `attributesCount`, `childrenCount`, etc.); a group's links/children/contents (i.e. the `name` and `kind` of every child); and an entity's attributes (names and values). We could follow this division in H5Web and have three (four) separate stores: `entitiesStore`, `childrenStore`, `attributesStore` (and `valuesStore`).

Of course, this would mean a lot more "suspended" components and potentially complex pre-fetching logic. The selection and expansion of a group would first require one request to get `childrenCount` and `attributeCount`, and then two parallel requests to get the children and attributes (for NeXUS) if needed. The selection of a dataset would require one request to get its `type` and `shape` (plus one request to get its value).

#### 3. Deal with attributes separately

We could implement a custom endpoint in each back-end to fetch a group's direct children with their metadata _but not their attributes_. We could then introduce a separate store for attributes and fetch them only when needed. I think this change would be more likely to be adopted by the back-ends. It would amount to combining `fetchMetadata` and `fetchContents` in Jupyter, and in changing `fetchGroup` in HSDS to return the direct children's metadata right away.

This would definitely be worthwhile for users with high-latency connections. It would also reduce the need for pre-fetching: we would typically pre-fetch only the newly expanded group's child groups instead of every single child. However, it is still unclear how attributes could be fetched efficiently, especially with regard to NeXUS.

**Comment by axelboc** [comment]
`getGroup` is now `getEntity(path: string): Entity` as explained in #424. I have edited the previous comment's _Proposed API_ sections.
