### ISSUE TITLE
Clickable breadcrumbs

### ISSUE THREAD

**Issue by loichuder** [silx-kit/h5web#454]
I thought we already had an issue for that... Well, what do I know

While breadcrumbs work fine, a common user interaction is to click on a crumb to navigate to the crumb level.

Ex:
![image](https://user-images.githubusercontent.com/42204205/106763935-9e4ccd80-6637-11eb-9ae5-b37a30d0e3e4.png)

Here, **results** is selected. One might expect to select **entry_0000** to display/inspect this group by clicking on it.

**Comment by axelboc** [comment]
Should be trivial, especially now that we work with paths.
