### ISSUE TITLE
[Heatmap] Color scheme selection

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#47]
Allow user to pick a different colour scheme -- https://github.com/d3/d3-scale-chromatic

**Comment by loichuder** [comment]
I looked into different solutions for the selector:
- [react-dropdown](https://github.com/fraserxu/react-dropdown): easy to set up but lack of customization
- [react-dropdown-select](https://github.com/sanusart/react-dropdown-select/): looks more promising, I have to test

There is also the [dropdown from React-Semantic-UI](https://react.semantic-ui.com/modules/dropdown/) that looks more complete but installing the whole package only for that...

**Comment by axelboc** [comment]
This might help as well: https://npms.io/search?q=react+dropdown

**Comment by loichuder** [comment]
Settled for [react-select](https://react-select.com/home) in the end
