### ISSUE TITLE
[Scalar] Boolean values

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#479]
A user has reported seeing the error `Expected number or string` when trying to visualize a `boolean` value. This error probably comes from `ScalarVis`. We need to investigate how this data type is exposed by the back-ends and how we should model it in our front-end models and providers.

**Comment by loichuder** [comment]
Probably related: https://github.com/jupyterlab/jupyterlab-hdf5/pull/66#discussion_r545680070
