### ISSUE TITLE
[Heatmap] Reverse any colour map

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#480]
A user has requested that a reverse grey colour map be added, and that it be part of the _Common_ colour maps.

This was in our plan, but were we thinking of allowing any colour map to be reversed (i.e. a toggle of some sort in the toolbar)? I can't remember. Adding a single reverse grey colour map is probably easier, though.

**Comment by loichuder** [comment]
I would advocate :avocado: to allow any colour map to be reversed. While adding a single reverse might seem easier, I think it will be cleaner in the code to implement a more general behaviour on all colour maps.

**Comment by loichuder** [comment]
Fixed by #500
