### ISSUE TITLE
[Line/Heatmap] Minimap

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#49]
It could be interesting to add a minimap for context. Here is an example: https://vx-demo.now.sh/zoom-i

The minimap itself could be interactive:
- drag the rectangle to pan;
- click to pan instantly to another location.

**Comment by axelboc** [comment]
This would have been fun, but I'm starting to doubt it's worth the effort. In our case, we really don't want the minimap to mask a part of the visualization... We could make it toggleable, but it defeats the purpose, I think. What do you think @loichuder?

**Comment by loichuder** [comment]
I agree, it sounded like a fun thing but it would need quite some digging into R3F/Three.js. And I think other improvements require our attention :wink:
