### ISSUE TITLE
Review the use of CSS variables

### ISSUE THREAD

**Issue by loichuder** [silx-kit/h5web#555]
Working on #470, we realized that setting line colors from CSS variables is a bit clunky and introduces obscure coupling between CSS and JS.

@axelboc proposed that we instead:
- use a `Provider` to explicitly set colors:
```jsx
<ThemeProvider theme="dark"> // or `theme={{ auxSignals: ['#000', '#111', '#222'] }}`
  <AppOrHeatmapOrWhatever />
</ThemeProvider>
```
- have then a hook `useTheme` that can return a default theme if the provider is not used
- use the `Provider` to read colors from the CSS or (the other way round) inject the colors in the CSS

**Comment by axelboc** [comment]
This will make disabling transparency on the WebGL renderer [for performance reasons](https://discoverthreejs.com/tips-and-tricks/#renderer)) possible, as it will be easy to access the canvas' background colour so it can be [passed to the scene](https://github.com/pmndrs/react-three-fiber/issues/304#issuecomment-743038591)

**Comment by axelboc** [comment]
After much thinking, I think a CSS-driven solution is cleaner and more flexible:

- Following @loichuder's investigation, it seems complicated to access the user's theme from JS in JupyterLab, which makes the idea of a `ThemeProvider` impractical. Overriding CSS custom properties based on the presence or absence of a `data-theme` attribute remains the most viable option.
- Users of `@h5web/lib` may not want to clutter their React application with a `ThemeProvider`. It seems overly complicated for users who just want to use one visualisation to have to add this provider.
- It is unclear whether a `ThemeProvider`-based solution would allow overriding variables contextually (e.g. in one part of the app but not another)
- We need access to the colours from React only in very few places, so adding this provider complexity to the React code seems unnecessary.

A CSS-driven solution allows for much more flexibility:

- Assuming we prefix our variables, users can just import a stylesheet in their project for all the variables to be made available on `:root`.
- If they prefer, users can declare only the variables they need where they need them.
- Users can easily override variables in some parts of their app and not others, or based on any CSS selector they choose (which makes it easy to change colours dynamically from React).

Reading the value of a CSS variable in React is not too complicated, and I've made a custom hook for it in #660. In the end, we'll probably need to use this hook only in the top-level visualization components, as low-level components like `DataCurve` can just accept valid colors as props (as done in #660).
