### ISSUE TITLE
Config from Vis1 is reset when changing datasets while being on Vis2

### ISSUE THREAD

**Issue by loichuder** [silx-kit/h5web#608]
To reproduce, we need two datasets that support the same two vis. I take `LineVis` as `Vis1` and `MatrixVis` as `Vis2` as example.

Steps:
1. Select dataset 1
1. Select the `LineVis`
1. Make a change in the LineConfig (e.g. change the scales)
1. Select the `MatrixVis`
1. Select the dataset 2. We land on the `MatrixVis`.
1. Select the `LineVis` -> **The LineConfig was reset**

Note that at step 4., the config is properly kept: we can switch between `MatrixVis` and `LineVis` without any change in the LineConfig.

**Comment by axelboc** [comment]
Fixed by #646
