### ISSUE TITLE
[Line] Slicing do not update the displayed data

### ISSUE THREAD

**Issue by loichuder** [silx-kit/h5web#614]
A render needs to be triggered for the data to update (e.g. zoom/pan)

**Comment by loichuder** [comment]
Unsurprisingly, the culprit is 8189b5867f29d71ad6ba17987ecbdb555369c7de :smile:

**Comment by axelboc** [comment]
Fixed with https://github.com/silx-kit/h5web/commit/b5de504107bf7a1768b9fb54ecadf539738fdb16
