### ISSUE TITLE
[NeXus] Error message when default is not found changes with the backend

### ISSUE THREAD

**Issue by loichuder** [silx-kit/h5web#618]
When the `default` attribute is not found (see group `default_not_found`), we get different error messages depending on the backend:
- [Mock](https://h5web.panosc.eu/mock): **Expected entity at path "/test"**
- [Jupyter](https://h5web.panosc.eu/?file=nexus_malformed.h5): **Request failed with status code 500**
- [HSDS](https://h5web.panosc.eu/hsds/?file=/home/reader/nexus_malformed) : **Expected some value**

Perhaps we could have a more appropriate and unified error message for this particular case.

For the record, the other error messages (`default_not_string`, `no_signal` and `signal_not_found`) are consistent and clear.

**Comment by axelboc** [comment]
Not a fan of the second approach after all. Will try a catch-and-rethrow approach instead.

**Comment by axelboc** [comment]
This issue concerns also the error message displayed when navigating to an entity that doesn't exist, notably when following a NeXus attribute like `axis` or `signal` in the metadata viewer.

The fix requires back-end providers to respond with a 404 to the request made from the `getEntity` API method. This is currently the case with HSDS, but not with H5Grove and jupyerlab-hdf5:

- [ ] https://github.com/jupyterlab/jupyterlab-hdf5/issues/96
- [ ] https://github.com/silx-kit/h5grove/issues/24

**Comment by axelboc** [comment]
Now fixed in all providers! :tada: :trophy:
