### ISSUE TITLE
Reword displayed message `Nothing to visualize` when no vis is available

### ISSUE THREAD

**Issue by loichuder** [silx-kit/h5web#620]
The message `Nothing to visualize` could imply that there is **absolutely nothing** to visualize in the whole file. Especially as it is displayed when landing on the root group.

Ideas:
1. `This entity cannot be visualized.`
2. `No visualization available for this entity.`
...

**Comment by axelboc** [comment]
For what it's worth, "Nothing to visualize at this level" would work only for groups, which complexifies things.

**Comment by t20100** [comment]
What about `No visualization available for this item`?
