### ISSUE TITLE
[Storybook] Discussion after quick review

### ISSUE THREAD

**Issue by loichuder** [silx-kit/h5web#623]
I had a quick look at the story book and would like to discuss the following points:

- [x] `[HeatmapVis]` Is the _Live Data_ story still relevant ?
- [x] `[HeatmapVis]` On _Scroll Capture_, zooming on the heatmap still make the page scroll (FF 87). Should we reopen #520 ?
- [x] `[ScalarVis]` Not the most interesting I agree, but should we add boolean and complex displays to the stories ?
- [x] `[ColorBar]` On _With Bounds_, the font size of bounds is much bigger than the one of the ticks. Perhaps we should change the styles so that the two font sizes are consistent ?

**Comment by axelboc** [comment]
> [HeatmapVis] Is the Live Data story still relevant ?

Nope, since we've removed the loader anyway.

> [HeatmapVis] On Scroll Capture, zooming on the heatmap still make the page scroll (FF 87). Should we reopen #520 ?

Must be a regression from the R3F upgrade, so yes.

> [ScalarVis] Not the most interesting I agree, but should we add boolean and complex displays to the stories ?

Sure!

> [ColorBar] On With Bounds, the font size of bounds is much bigger than the one of the ticks. Perhaps we should change the styles so that the two font sizes are consistent ?

Hmm not sure. We could increase the font size of the ticks a bit, but it's good that the bounds stand out more.

**Comment by loichuder** [comment]
> Hmm not sure. We could increase the font size of the ticks a bit, but it's good that the bounds stand out more.

I agree. I meant that we could change the styles so that the ratio of sizes between the ticks and bounds stay consistent.
