### ISSUE TITLE
Show axes when grid is off

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#692]
When `showGrid` is `false`, both in the Line and Heatmap vis, perhaps we should still show the axes?

![image](https://user-images.githubusercontent.com/2936402/121325200-b1d3b200-c911-11eb-8221-823e305fab72.png)

**Comment by loichuder** [comment]
Something like this ?
![image](https://user-images.githubusercontent.com/42204205/121334965-74bfed80-c91a-11eb-8d64-26e2ae4b7ee3.png)

**Comment by axelboc** [comment]
hmm more like on `0, 0`

**Comment by loichuder** [comment]
> Hmm more like on `0, 0` ... but then the ticks would still be floating in mid-air ... Could we find a way to extend the ticks only up to the `0` line?

But then, ticks will still be floating when zooming. I think adding some kind of "frame" around the canvas would be our best bet

**Comment by axelboc** [comment]
Right, yeah. Maybe just a very subtle one then.
