### ISSUE TITLE
Typescript 4.3 breaks the storybook

### ISSUE THREAD

**Issue by loichuder** [silx-kit/h5web#696]
The error comes from `react-docgen-typescript`: https://github.com/styleguidist/react-docgen-typescript/issues/356. 

`react-docgen-typescript` is requested by `react-docgen-typescript-plugin` that is requested by `@storybook/react`.

The [new version of react-docgen-typescript](react-docgen-typescript) fixes this but we should perhaps revert to TS 4.2 while the new version goes up the full dep chain ?

**Comment by axelboc** [comment]
Or do this: https://github.com/styleguidist/react-docgen-typescript/issues/356#issuecomment-857887751

**Comment by loichuder** [comment]
Temporary fix by #697 

Leaving this open until we can update to the new version of react-docgen-typescript
