### ISSUE TITLE
[Heatmap] Orthonormal coordinates

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#70]
- Allow switching to a orthonormal coordinate system where the x and y axis share the same unit of length.
- Let the heatmap expand to fit its container while maintaining the resulting aspect ratio (e.g. 1000x800 => 0.8). `object-fit: contain` might help with this.

**Comment by loichuder** [comment]
It is rather keeping the original aspect ratio of the heatmap. An image of 800x800 would indeed have an aspect ratio of 1 but an image of 1000x800 would need to keep its aspect ratio of 0.8.
