### ISSUE TITLE
Axis-to-dimension mapping

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#73]
Allow selecting which dimension should be displayed on which axis. This applies to the Matrix, Line and Heatmap visualizations.

> Ideally swapping two axis should take a single click and not require a intermediate step where the same dimension is displayed on two axis.

**Comment by axelboc** [comment]
As discussed, the "Dimension Mapper" takes the shape of a panel on the left-hand side of the visualization area. The panel has a collapsed/expanded state.

When expanded, the panel shows two button groups labelled `x` and `y` listing the indices of the current dataset's dimensions. The second last and last dimensions are selected for by default `x` and `y`, respectively. When changing the dimension for `x`/`y`, if the newly selected dimension is already assigned to `y`/`x`, then the two dimensions are swapped.

When expanded, still, the panel also shows vertical sliders for every dimension not currently assigned to `x` or `y`. The sliders are ordered in ascending order of dimension from left to right. When the slider dimensions change because of a change in `x` and `y`, the sliders are reset to 0. A spread-out button group sits above the dimension sliders, allowing to select which slider is to remain visible when the panel is collapsed. The last dimension slider (the one on the right) is selected by default.

When collapsed, the panel shows the dimensions assigned to `x` and `y`, as well as the selected dimension slider. The panel is collapsed by default when opening a dataset, but the collapsed/expanded state will eventually be persisted as per #94.

![axis-dim-mapping](https://user-images.githubusercontent.com/2936402/82638973-15f0de80-9c08-11ea-99f8-95df9ca2ffb7.png)

**Comment by axelboc** [comment]
The expand/collapse feature does not seem to be needed after all. The mapper looks fine with multiple sliders. Most datasets won't have more than 3 dimensions (i.e. 1 slider) anyway.

**Comment by axelboc** [comment]
For reference, the only remaining work on this is #170.

**Comment by axelboc** [comment]
Closing this epic, as #170 may take a while and it works reasonably well as it is now. Getting back into the code of `HeatmapVis`, I'm really glad we decided to put the dimension mapping one level higher so the visualization components don't have to know anything about it!

**Comment by loichuder** [comment]
Agreed. I will prepare #178 for merging so that we implement what we can do for now, and keep the rest for another MR.
