### ISSUE TITLE
[Line] Log scale for axis

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#74]

**Comment by axelboc** [comment]
Perhaps a stupid question: is this relevant at all to the dimensional axis (i.e. the `x` axis)?

**Comment by loichuder** [comment]
Not a stupid question: it really depends what you are displaying on the axis in question. This has to be solved with #73 but I think the possibility should exist on both axes.

**Comment by loichuder** [comment]
#133 implemented a [SymLog](https://www.researchgate.net/publication/233967063_A_bi-symmetric_log_transformation_for_wide-range_data) scale as it was simpler to implement for data that contain negative or null values. 

We need to decide how to implement the regular log scale that only works for strictly positive values. Possibilities include:
1. Deactivate the log scale button when the data contain negative or null values.
2. Display only the positive values on which the log transformation was able to be done.

**Comment by axelboc** [comment]
3. Choose dynamically which log scale to apply and make that clear to the user.

But as discussed, perhaps the symlog scale is a satisfactory solution for the viewer, as users can export the data and run their own analysis.
