### ISSUE TITLE
Cividis and Turbo colormaps are not implemented

### ISSUE THREAD

**Issue by loichuder** [silx-kit/h5web#77]
We are depending on `@types/d3-scale-chromatic` which [only supports d3-scale-chromatic 1.3.2](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/d3-scale-chromatic/index.d.ts#L9) while Cividis and Turbo are implemented in [d3-scale-chromatic 1.5.0](https://github.com/d3/d3-scale-chromatic/releases).

_Originally posted by @loichuder in https://github.com/silx-kit/h5web/pull/61_

**Comment by axelboc** [comment]
I've opened a PR on DefinitelyTyped https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43917

**Comment by axelboc** [comment]
The PR has been merged and a new version of `@types/d3-scalar-chromatic` has been released. 🎉
