### ISSUE TITLE
[SqrtScale] Domain can be `[0, max]` even when data doesn't contain `0`

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#789]
On line 353 of `src\h5web\vis-packs\core\utils.ts`, in `getValidDomainForScale()`, we have this code:

```ts
  if (scaleType === ScaleType.Sqrt && min * max < 0) {
    return [0, max];
  }
```

I'm thinking that this can potentially return a min bound that doesn't actually match the min "safe" value of the data. If the data is `[-1, 1, 2]`, for instance, then the returned domain will be `[0, 2]` instead of `[1, 2]`.

The `Bounds` object should probably include an additional  property (`positiveOrZeroValue`, perhaps?)

**Comment by loichuder** [comment]
It depends what you wish for.

`getValidDomainForScale` could return
- the valid domain with the maximum extension that is included in `dataDomain` with no restrictions. In a case of a domain crossing 0, this would be `[0, max]` for `Sqrt` and `[MIN_VALUE, max]` for `Log`.
**or**
- the valid domain with the maximum extension that is included in `dataDomain` but clamped to data points. In a case of a domain crossing 0, this would be `[positive_min, max]` for `Sqrt` and `[strict_positive_min, max]` for `Log`.

This being said, my reasoning highlights that the behaviour is not consistent between `Sqrt` and `Log`.

**Comment by loichuder** [comment]
> The `Bounds` object should probably include an additional property (`positiveOrZeroValue`, perhaps?)

Or have `strictPositiveMin` and `positiveMin` instead of only `positiveMin` (that is strictly positive for now) ?

**Comment by axelboc** [comment]
> This being said, my reasoning highlights that the behaviour is not consistent between Sqrt (is currently case 1) and Log (is currently case 2).

Yeah, and I don't think we ever need case 1 in the codebase, as far as I know.
