### ISSUE TITLE
Put CSS in exports ?

### ISSUE THREAD

**Issue by loichuder** [silx-kit/h5web#832]
I am trying to make jupyterlab_h5web into a JupyterLab pre-built extension: https://github.com/silx-kit/jupyterlab-h5web/pull/50

Unfortunately, the building of the extension fails because it cannot resolve the `@h5web/app` CSS I need to import:

```
ModuleNotFoundError: Module not found: Error: Package path ./dist/style-lib.css is not exported from package .../jupyterlab-h5web/node_modules/@h5web/app (see exports field in .../jupyterlab-h5web/node_modules/@h5web/app/package.json)
```

<details>
<summary>Error callstack</summary>
<pre>
    at .../jupyterlab-h5web/node_modules/webpack/lib/Compilation.js:2004:28
    at.../jupyterlab-h5web/node_modules/webpack/lib/NormalModuleFactory.js:795:13
    at eval (eval at create (.../jupyterlab-h5web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)
    at .../jupyterlab-h5web/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (.../jupyterlab-h5web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at .../jupyterlab-h5web/node_modules/webpack/lib/NormalModuleFactory.js:431:22
    at .../jupyterlab-h5web/node_modules/webpack/lib/NormalModuleFactory.js:124:11
    at .../jupyterlab-h5web/node_modules/webpack/lib/NormalModuleFactory.js:667:25
    at .../jupyterlab-h5web/node_modules/webpack/lib/NormalModuleFactory.js:852:8
    at .../jupyterlab-h5web/node_modules/webpack/lib/NormalModuleFactory.js:972:5
.../jupyterlab-h5web/node_modules/@jupyterlab/builder/lib/build-labextension.js:100
</pre>
</details>

Should we include the CSS in the `exports` field of the package ?

Some issues for reference:
- https://github.com/jupyterlab/jupyterlab/issues/9948
- Another package that had the same issue: https://github.com/brianvoe/slim-select/issues/269

**Comment by axelboc** [comment]
Yeah sounds good. We can take the opportunity to shorten the import path too:

```css
    "./style-lib.css": {
      "require": "./dist/style-lib.css",
      "import": "./dist/style-lib.css"
    },
    "./style.css": {
      "require": "./dist/style.css",
      "import": "./dist/style.css"
    }
```
