### ISSUE TITLE
NX badge is shown for NX entities without valid implicit default child and not shown for not-NX entities with a valid implicit default child

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#846]
See https://github.com/silx-kit/h5web/pull/845#discussion_r748290911

- **False positive**: the NX badge is shown for an entity with class `NXprocess` or `NXentry`, even though such an entity is not guaranteed to have an implicit default child.
- **False negative**: the NX badge is not shown for an entity that doesn't have class `NXprocess` or `NXentry`, even though such an entity may have an implicit default child.

The above cases only relate to implicit default child resolution. Entities with explicit `default` attributes are not concerned by these false positives/negatives.

Arguably, these cases should not occur in a well-structured NeXus file; they occur only because we chose to be forgiving in the default entity resolution algorithm. So I see a few options:

1. Ignore the issue and accept the potential inconsistency between the NX badge and the default entity resolution.
2. Make the default entity resolution stricter.
3. Make the NX badge consistent with the resolution by calling `resolvePath` and fetching all child entities ahead of time (bad idea, since it would break all our fetching optimisations).
4. Mitigate the issue by updating the NX badge once the user has clicked on an entity with a false positive/negative (very challenging with the current implementation of the `Explorer`).

My vote goes to the first option. I think the current state of considering the NX badge as a "best-guess" indicator is a good compromise in terms of UX.

**Comment by loichuder** [comment]
> 1. Ignore the issue and accept the potential inconsistency between the NX badge and the default entity resolution.

I agree. Given that these are edge-cases that derive from inconsistency in the file, I see it as a minor problem.
