### ISSUE TITLE
Ordinate label can appear above tick labels

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#903]
![image](https://user-images.githubusercontent.com/2936402/145815263-5a4ef7f2-5b80-41b4-bc82-96262d9996fe.png)

**Comment by loichuder** [comment]
Can be seen also in `/surface_file` plot of https://h5web.panosc.eu/h5wasm?url=https%3A%2F%2Fraw.githubusercontent.com%2Foasys-esrf-kit%2Fdabam2d%2Fmain%2Fdata%2Fdabam2d-001.h5

**Comment by loichuder** [comment]
Issue also raised in visx (that renders the axis): https://github.com/airbnb/visx/issues/1395

**Comment by axelboc** [comment]
[Playing with](https://observablehq.com/@d3/d3-format) some [D3 formats](https://github.com/d3/d3-format#locale_format):

### `.3~g`

```js
d3.format(".3~g")(3234234234234452) // 3.23e+15 (B)
d3.format(".3~g")(123452) // 1.23e+5
d3.format(".3~g")(122) // 122
d3.format(".3~g")(1) // 1 (C)
d3.format(".3~g")(0.12342354345) // 0.123
d3.format(".3~g")(0.0000012342354345) // 0.00000123 (A)
d3.format(".3~g")(0.00000012342354345) // 1.23e-7
d3.format(".3~g")(0.0000000000012342354345) // 1.23e-12
```

- (A) max length of 10 characters. It's weird; I would expect exponent notation to kick in right from `0.0xxx`...
- (B) length of 8, which is what I would have expected the max length to be.
- (C) min length of 1.

### `.3~s`

```js
d3.format(".3~s")(3234234234234452) // 3.23P
d3.format(".3~s")(123452) // 123k
d3.format(".3~s")(122) // 122
d3.format(".3~s")(1) // 1
d3.format(".3~s")(0.12342354345) // 123m
d3.format(".3~s")(0.0000012342354345) // 1.23µ
d3.format(".3~s")(0.00000012342354345) // 123n
d3.format(".3~s")(0.0000000000012342354345) // 1.23p
```

This is a lot more stable with 5 characters max. But do we want SI prefixes even when axes don't have units?

**Comment by loichuder** [comment]
`g` is in fact an alias for `Number.toPrecision`.

`s` is indeed the best candidate to get fixed-width strings. I am not a huge fan of prefixes but it could be an option to activate :shrug:
