### ISSUE TITLE
[MatrixVis] Output is not readable for arrays of long strings.

### ISSUE THREAD

**Issue by loichuder** [silx-kit/h5web#916]
### Describe the bug

In the MatrixVis, elements of arrays are displayed in cells that have a fixed width and height. These dimensions are quite small as they are appropriate for numbers.

As a consequence, arrays containing long strings make unreadable cells. This is unfortunate as MatrixVis is the only vis for arrays of strings (dtype `S`).

### To Reproduce

1. Go to https://h5web.panosc.eu/?file=epics.h5
2. Click on `A note`
3. See long strings cramped in small cells

### Expected behaviour

As far as I remember, cell dimensions are fixed to allow for virtualisation of the matrix so we cannot use flex or similar fit-to-content tricks.

Given that the length of strings is part of the dtype, we could increase the cell width accordingly when mounting the component.

### Screenshots
![image](https://user-images.githubusercontent.com/42204205/148072107-572572c3-8ff7-469d-b899-9b004fd0ac32.png)

**Comment by axelboc** [comment]
> Given that the length of strings is part of the dtype, we could increase the cell width accordingly when mounting the component.

That may not always be the case, though -- the dtype could be `VLEN`.
