### ISSUE TITLE
Large mixed type dataset logged to the console can be missleading

### ISSUE THREAD

**Issue by t20100** [silx-kit/h5web#917]
### Describe the bug

Too large to display mixed type dataset leads to the message: `The dataset is too big to be displayed and was logged to the console instead.`
This seems missleading to me, since not everyone will look into the dev tools to open the console.

### To Reproduce

1. Go to https://h5web.panosc.eu/?file=epics.h5
2. Click on `arrays` -> `Vdata with mixed types`
4. Message is: `The dataset is too big to be displayed and was logged to the console instead.`

### Expected behaviour

To avoid missleading message:
- the data could not be displayed at all: `The dataset is too big to be displayed.`, or
- the data could be displayed on-demand: `This dataset is big,` [`display it`](), if possible with a foldable json viewer.

### Context

- H5Web context: demo

**Comment by axelboc** [comment]
The initial problem was that the browser would get stuck while parsing/displaying large JSON outputs. So we could also look for a way to solve this performance issue with an external library that parses JSON asynchronously and can render it in a virtualized way.
