### ISSUE TITLE
H5Web is no longer just a stand-alone HDF5 viewer

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#926]
We should update the README(s) to convey that H5Web is more than a stand-alone viewer and that the library can be used to visualize data arrays from any source. We should also update the GIF, since the UI has evolved a little since it was recorded.

**Comment by axelboc** [comment]
While we're at it, we can add more example files and maybe make them links for convenience.

**Comment by loichuder** [comment]
We have the GIF that demonstrates `@h5web/app` but I think we should add some screenshots of `@h5web/lib` to highlight more the visualization capabilities. 

We could for example add screenshots of the example codesandboxes below the links ?
