### ISSUE TITLE
Investigate zooming sensitivity on Mac laptop

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#93]
The touchpad seems to be quite sensitive between two-finger scroll (heatmap zoom) and two-finger pinch (browser zoom). Perhaps we should mitigate this by canceling _some_ pinch events. We'll have to test this on a Mac laptop at some point.

**Comment by t20100** [comment]
Just tested with firefox on a macos laptop (from late 2015...) and it works fine
