### ISSUE TITLE
Persist application state

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#94]
This is a very high-level issue for now. Here are some initial ideas:

- Persist inspect/display state.
- Persist open/closed state of groups in explorer.
- Persist selected node and expanded groups in explorer.
- Persist explorer width if resized.
- Persist selected visualization.
- [x] Persist visualization options - cf. #72  
- Persist some states to the URL (inspect/display, selected node, selected visualization, visualization options, etc.)?

We can play with different amounts of persistence and technical solutions:

- Persistence during a session - i.e. restore state when unmounting then remounting a component:
  - move state up the component hierarchy;
  - make state global.
- Persistence across sessions - i.e. restore state when closing then re-opening the app in the same browser:
  - `localStorage` - e.g. UI settings;
  - cookies - e.g. authentication.
- Persistence across environments:
  - URL - e.g. navigation;
  - server-side database - e.g. permalink generation, authenticated settings, etc.

**Comment by loichuder** [comment]
Note that since `3.1.4`, zustand has a [middleware](https://github.com/pmndrs/zustand#persist-middleware) to persist stores. For the record, the zustand dep was updated to 3.2.0 in #335. 

The downside with respect to our implementation is that there is no filtering on which store entries should be persisted (all or nothing).

**Comment by axelboc** [comment]
Closing for now. We're persisting the state of most toolbar controls, and the URL of some provider demos allows viewing a specific "domain" (i.e. file). Let's wait for more specific user feedback.
