### ISSUE TITLE
[NX Spectrum] Legend and tooltip values for auxiliary signals

### ISSUE THREAD

**Issue by tomio13** [silx-kit/h5web#970]
## Plotting multiple curves
based on the auxiliary signal in data file has no indication of which signal is which. Moving the cursor around also shows only data related to one curve, thus no help.

It would be great to have a **legend** which could be called up on the side indicating which color / curve type belongs to which signal.

**Comment by axelboc** [comment]
Hi @tomio13, we now show the names and values of the auxiliary signals in the tooltip:

![image](https://user-images.githubusercontent.com/2936402/161081589-3508ce98-c420-455a-beb2-cad02b5da4d9.png)

Next, I was thinking of adding the colours of the auxiliary signals (and of the main plot) to the tooltip as well, which, in a way, makes the tooltip acts as a legend. So my question is: would that be sufficient, do you think, or would you still need a separate legend in the bottom right corner?

**Comment by axelboc** [comment]
PR open to add plot colors to the tooltip:

![image](https://user-images.githubusercontent.com/2936402/161242604-42aa6133-7a6d-4888-b429-40f11aea1e80.png)

I'll wait to hear back from you and your team, @tomio13, before implementing a separate legend, as I feel like this version of the tooltip solves the initial issue of identifying which plot is which.

**Comment by tomio13** [comment]
@axelboc : Thank you, this looks quite great.
I think, this is excellent for live view and handling of the data.
A legend is necessary then whenever the user tries to export / print the plot.

**Comment by axelboc** [comment]
Great! I'll close this issue then. I've opened #1050 to deal with exporting visualisations as images, as this is not something that is currently implemented at all.

**Comment by tomio13** [comment]
Thanks!
