### ISSUE TITLE
Improvements for selection-based zoom

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#993]
- [x] #999
- [x] #998
- [x] #997
- [x] #1003
- [x] #994
- [x] #1025
- [x] #1055
- [x] #1057
- [x] #1076

**Comment by loichuder** [comment]
> On the heatmap vis, it is sometimes difficult to see the selection rectangle due to poor contrast. We could imagine giving it a subtle white background?

On this, I will add that there is an inconsistent behaviour on dark mode: the rectangle color gets inverted for the `LineVis` and `Scatter` but not for the `Heatmap` nor the `RgbVis`.

**Comment by axelboc** [comment]
@t20100 mentioned that in Silx and other software, when the ratio has to be kept, the area that the user selects must be fully visible once the zoom is applied. This means that the rectangle that shows the area that will be zoomed on would be the outter rectangle, not the inner rectangle. This behaviour also means that the outter selection rectangle must be properly constrained to the bounds of the visualization. Here's a mock-up for a selection where the pointer leaves the bounds of the heatmap -- the outter, continuous rectangle would be the area that is actually zoomed on:

![selection](https://user-images.githubusercontent.com/2936402/156601405-82d1cbd3-fa5c-4972-9019-692d2738d243.png)

**Comment by loichuder** [comment]
:fireworks:
